(function(){
  const body=document.body,root=document.documentElement;
  const savedLang=localStorage.getItem('nrw_page_lang')||'en';
  const savedTheme=localStorage.getItem('nrw_theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
  body.dataset.lang=savedLang;root.lang=savedLang;root.dataset.theme=savedTheme;
  const themeBtn=document.getElementById('themeBtn');
  const setThemeIcon=()=>themeBtn.textContent=root.dataset.theme==='dark'?'☀':'☾';setThemeIcon();
  themeBtn.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('nrw_theme',root.dataset.theme);setThemeIcon()});
  document.querySelectorAll('[data-lang-btn]').forEach(btn=>{btn.classList.toggle('active',btn.dataset.langBtn===savedLang);btn.addEventListener('click',()=>{body.dataset.lang=btn.dataset.langBtn;root.lang=btn.dataset.langBtn;localStorage.setItem('nrw_page_lang',btn.dataset.langBtn);document.querySelectorAll('[data-lang-btn]').forEach(x=>x.classList.toggle('active',x===btn));renderDynamic()})});

  const i18n={
    de:{locale:'de-DE',today:'Heute',tomorrow:'Morgen',done:'Täglich',important:'Wichtig',bearTodayTag:'HEUTE',bearNextTag:'NÄCHSTER TERMIN',genTomorrowTag:'MORGEN',genNowTag:'JETZT VERFÜGBAR',bearToday:'Heute ist Bärenfalle. Die nächste findet am {date} statt.',bearNext:'Nächste Bärenfalle: {date}. Danach wieder alle zwei Tage.',
      tasks:[['🎁','Gratis & täglich abholen','VIP, Händler, Arena, Allianzgeschenke und kostenlose Shop-Angebote einsammeln.','Täglich'],['🪖','Truppen clever vorbereiten','Normal weiter ausbilden. Vor punktestarken Trainingstagen lange Ausbildungen so timen, dass sie dort enden.','Planen'],['⛏️','Sammler vorausplanen','Märsche vor dem Reset losschicken, wenn morgen Sammelpunkte zählen. Sonst gleichmäßig Ressourcen sichern.','Planen']],
      bearTask:['🐻','Bärenfalle vorbereiten','Märsche zurückholen, richtige Joiner-Helden setzen und kurz vor BT1/BT2 online sein. Discord-Ansagen beachten.','Wichtig'],
      specialTask:['🔄','Transferphase im Blick behalten','Server 1044 liegt im aktuellen Transferfenster. Änderungen und Allianzabsprachen zuerst im Discord prüfen.','Heute'],
      nextHero:'Morgen auf Server 1044',tomorrowItems:[['⚔️','Allianzgemenge startet','Vor dem Einsatz von Ressourcen zuerst die aktiven Aufgaben und Belohnungsstufen prüfen.'],['🏛️','Handelsimperium startet','Tägliche und kostenlose Möglichkeiten früh mitnehmen; größere Ausgaben mit dem NRW-Plan abstimmen.'],['🧙','Neuer Meister','Per Ingame-Mitteilung für morgen angekündigt. Der Name wurde noch nicht veröffentlicht.'],['🔄','Helden-Splittertausch startet','Tauschbare Splitter und Konditionen zuerst kontrollieren. Wertvolle Splitter nicht ungeprüft einsetzen.'],['✨','Generation 6 wird freigeschaltet','Triton, Sophia und Yang kommen laut K1044-Timeline. Goldschlüssel und universelle Splitter zunächst zurückhalten.']],
      genericTomorrow:'Morgen vorbereiten',genericTomorrowItems:[['📅','Event-Vorschau prüfen','Nach dem täglichen Reset die aktuellen Events kontrollieren.'],['⏱️','Abschlüsse planen','Sammler und lange Truppenausbildungen erst nach dem nächsten Punkteplan abschließen.']]},
    en:{locale:'en-GB',today:'Today',tomorrow:'Tomorrow',done:'Daily',important:'Important',bearTodayTag:'TODAY',bearNextTag:'NEXT DATE',genTomorrowTag:'TOMORROW',genNowTag:'AVAILABLE NOW',bearToday:'Bear Trap is today. The next one is on {date}.',bearNext:'Next Bear Trap: {date}. Then again every two days.',
      tasks:[['🎁','Collect free daily rewards','Claim VIP, trader, arena, alliance gifts and free shop offers.','Daily'],['🪖','Prepare troops intelligently','Keep training normally. Time long batches to finish on high-value troop training days.','Plan'],['⛏️','Plan gatherers ahead','Send marches before reset when gathering scores tomorrow. Otherwise keep resources flowing steadily.','Plan']],
      bearTask:['🐻','Prepare for Bear Trap','Recall marches, set the correct joiner heroes and be online shortly before BT1/BT2. Follow Discord calls.','Important'],
      specialTask:['🔄','Watch the transfer phase','Server 1044 is in the current transfer window. Check Discord first for changes and alliance coordination.','Today'],
      nextHero:'Tomorrow on Server 1044',tomorrowItems:[['⚔️','Alliance Brawl starts','Check the active tasks and reward tiers before spending resources.'],['🏛️','Trade Empire starts','Complete daily and free opportunities early; coordinate larger spending with the NRW plan.'],['🧙','New Master','Announced for tomorrow in an in-game notice. The name has not been revealed yet.'],['🔄','Hero Shard Exchange starts','Check eligible shards and exchange conditions first. Do not trade valuable shards blindly.'],['✨','Generation 6 unlocks','Triton, Sophia and Yang arrive according to the K1044 timeline. Hold Gold Keys and universal shards initially.']],
      genericTomorrow:'Prepare for tomorrow',genericTomorrowItems:[['📅','Check the event preview','Review the active events after daily reset.'],['⏱️','Plan completions','Only finish gatherers and long troop batches after checking the next scoring plan.']]},
    fr:{locale:'fr-FR',today:"Aujourd’hui",tomorrow:'Demain',done:'Quotidien',important:'Important',bearTodayTag:"AUJOURD’HUI",bearNextTag:'PROCHAINE DATE',genTomorrowTag:'DEMAIN',genNowTag:'DISPONIBLE',bearToday:'Le Piège à ours a lieu aujourd’hui. Le prochain sera le {date}.',bearNext:'Prochain Piège à ours : {date}. Puis tous les deux jours.',
      tasks:[['🎁','Récupérer les récompenses gratuites','Récupère VIP, marchand, arène, cadeaux d’alliance et offres gratuites.','Quotidien'],['🪖','Préparer les troupes intelligemment','Continue l’entraînement. Fais terminer les longues séries lors des journées de points de troupes.','Planifier'],['⛏️','Planifier les collecteurs','Envoie les marches avant le reset si la collecte rapporte demain. Sinon, continue à sécuriser des ressources.','Planifier']],
      bearTask:['🐻','Préparer le Piège à ours','Rappelle les marches, choisis les bons héros et sois en ligne avant BT1/BT2. Suis les annonces Discord.','Important'],
      specialTask:['🔄','Surveiller la phase de transfert','Le serveur 1044 est dans la fenêtre de transfert actuelle. Vérifie d’abord Discord pour les changements.','Aujourd’hui'],
      nextHero:'Demain sur le serveur 1044',tomorrowItems:[['⚔️',"L’Alliance Brawl commence",'Vérifie les tâches actives et les paliers de récompenses avant de dépenser des ressources.'],['🏛️',"L’Empire commercial commence",'Profite tôt des tâches quotidiennes et gratuites ; coordonne les grosses dépenses avec le plan NRW.'],['🧙','Nouveau Maître','Annoncé pour demain dans un message en jeu. Le nom n’a pas encore été révélé.'],['🔄',"L’échange de fragments commence",'Vérifie d’abord les fragments acceptés et les conditions. Ne dépense pas les fragments précieux sans contrôle.'],['✨','La génération 6 arrive','Triton, Sophia et Yang arrivent selon la chronologie K1044. Garde d’abord les clés d’or et fragments universels.']],
      genericTomorrow:'Préparer demain',genericTomorrowItems:[['📅',"Vérifier l’aperçu",'Consulte les événements actifs après le reset quotidien.'],['⏱️','Planifier les fins',"Ne termine collectes et longs entraînements qu’après avoir vérifié le prochain plan de points."]]}
  };

  const anchor=Date.UTC(2026,8,13),day=86400000;
  const dateKey=d=>d.toISOString().slice(0,10);
  const isBearDay=d=>Math.round((Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-anchor)/day)%2===0;
  function nextBearAt(hour,minute){let d=new Date();for(let add=0;add<4;add++){const x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()+add,hour,minute));if(isBearDay(x)&&x>d)return x}return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()+2,hour,minute))}
  function fmtCountdown(target){let s=Math.max(0,Math.floor((target-Date.now())/1000)),days=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return (days?days+'d ':'')+[h,m,sec].map(v=>String(v).padStart(2,'0')).join(':')}
  function card([icon,title,copy,status],special=false){return `<article class="task"><div class="task-icon">${icon}</div><div><h3>${title}</h3><p>${copy}</p></div><span class="task-status ${special?'important':''}">${status}</span></article>`}
  function renderDynamic(){const lang=body.dataset.lang||'en',t=i18n[lang],now=new Date(),todayUTC=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())),tomorrow=new Date(todayUTC.getTime()+day),locale=t.locale;
    document.getElementById('weekday').textContent=now.toLocaleDateString(locale,{weekday:'long',timeZone:'UTC'});
    document.getElementById('dateLabel').textContent=now.toLocaleDateString(locale,{day:'2-digit',month:'short',timeZone:'UTC'}).toUpperCase();
    let tasks=[...t.tasks];if(dateKey(todayUTC)==='2026-09-14')tasks=t.tomorrowItems.map(([icon,title,copy])=>[icon,title,copy,t.today]).concat(tasks);if(isBearDay(todayUTC))tasks.unshift(t.bearTask);if(dateKey(todayUTC)==='2026-09-13')tasks.splice(1,0,t.specialTask);document.getElementById('todayTasks').innerHTML=tasks.map((x,i)=>card(x,i<2&&(isBearDay(todayUTC)||dateKey(todayUTC)==='2026-09-14'))).join('');
    const genTomorrow=dateKey(tomorrow)==='2026-09-14';document.getElementById('tomorrowTitle').textContent=genTomorrow?t.nextHero:t.genericTomorrow;document.getElementById('tomorrowTasks').innerHTML=(genTomorrow?t.tomorrowItems:t.genericTomorrowItems).map(([icon,title,copy])=>`<div class="tomorrow-task"><span>${icon}</span><div><strong>${title}</strong><small>${copy}</small></div></div>`).join('');
    const nextDay=nextBearAt(17,0),todayTrapEnd=new Date(todayUTC.getTime()+18.5*3600000),dateFmt=d=>d.toLocaleDateString(locale,{weekday:'long',day:'2-digit',month:'2-digit',timeZone:'UTC'});
    const followingBear=isBearDay(todayUTC)&&now<todayTrapEnd?new Date(todayUTC.getTime()+2*day):nextDay;
    document.getElementById('bearTag').textContent=isBearDay(todayUTC)&&now<todayTrapEnd?t.bearTodayTag:t.bearNextTag;
    document.getElementById('genTag').textContent=genTomorrow?t.genTomorrowTag:t.genNowTag;
    document.getElementById('bearDateNote').textContent=(isBearDay(todayUTC)&&now<todayTrapEnd?t.bearToday:t.bearNext).replace('{date}',dateFmt(followingBear));
  }
  function tick(){const now=new Date();document.getElementById('utcClock').textContent=now.toLocaleTimeString('en-GB',{hour12:false,timeZone:'UTC'});document.getElementById('bt1Countdown').textContent=fmtCountdown(nextBearAt(17,0));document.getElementById('bt2Countdown').textContent=fmtCountdown(nextBearAt(18,30));const gen6=new Date('2026-09-14T00:00:00Z');document.getElementById('gen6Countdown').textContent=gen6>now?fmtCountdown(gen6):({de:'Freigeschaltet',en:'Unlocked',fr:'Débloqué'}[body.dataset.lang]||'Unlocked');document.querySelectorAll('[data-count-to]').forEach(el=>{const d=new Date(el.dataset.countTo);el.textContent=d>now?fmtCountdown(d):({de:'Jetzt verfügbar',en:'Available now',fr:'Disponible'}[body.dataset.lang]||'Available now')})}

  const profileKey='nrw_member_profile_v1',playerNameInput=document.getElementById('playerName'),playerIdInput=document.getElementById('playerId');try{const p=JSON.parse(localStorage.getItem(profileKey)||'null');if(p){playerNameInput.value=p.playerName||'';playerIdInput.value=p.playerId||'';document.querySelectorAll('#languageGrid input').forEach(i=>i.checked=(p.languages||[]).includes(i.value))}}catch(e){}
  const messages={de:{missing:'Bitte Name, Player ID und Sprache angeben.',invalid:'Die Player ID darf nur Zahlen enthalten.',saved:'Im NRW-Spielerprofil gespeichert ✓',queued:'Zur Prüfung gespeichert ✓',error:'Speichern gerade nicht möglich.'},en:{missing:'Please add name, Player ID and language.',invalid:'Player ID must contain numbers only.',saved:'Saved to your NRW member profile ✓',queued:'Saved for review ✓',error:'Could not save right now.'},fr:{missing:'Ajoute ton nom, Player ID et ta langue.',invalid:'La Player ID doit contenir uniquement des chiffres.',saved:'Enregistré dans ton profil NRW ✓',queued:'Enregistré pour vérification ✓',error:'Enregistrement impossible.'}};
  document.getElementById('saveProfile').addEventListener('click',async()=>{const lang=body.dataset.lang||'en',m=messages[lang],status=document.getElementById('saveStatus'),button=document.getElementById('saveProfile'),profile={schemaVersion:2,playerName:playerNameInput.value.trim(),playerId:playerIdInput.value.trim(),languages:[...document.querySelectorAll('#languageGrid input:checked')].map(i=>i.value),otherLanguage:'',source:'nrw-player-dashboard',updatedAt:new Date().toISOString()};status.className='';if(!profile.playerName||!profile.playerId||!profile.languages.length){status.textContent=m.missing;status.className='error';return}if(!/^\d+$/.test(profile.playerId)){status.textContent=m.invalid;status.className='error';return}button.disabled=true;try{const r=await fetch('https://bdzlgirowutasrsycjfj.supabase.co/functions/v1/nrw-welcome-language',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)}),data=await r.json().catch(()=>({}));if(!r.ok||!data.ok)throw new Error();localStorage.setItem(profileKey,JSON.stringify(profile));status.textContent=data.queued?m.queued:m.saved;status.className='success'}catch(e){status.textContent=m.error;status.className='error'}finally{button.disabled=false}});
  renderDynamic();tick();setInterval(tick,1000);setInterval(renderDynamic,60000);
})();
