(function(){
  const body=document.body,root=document.documentElement,day=86400000;
  let eventFeed=[];
  const savedLang=localStorage.getItem('nrw_page_lang')||'en';
  const savedTheme=localStorage.getItem('nrw_theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
  body.dataset.lang=savedLang;root.lang=savedLang;root.dataset.theme=savedTheme;
  const themeBtn=document.getElementById('themeBtn');
  const setThemeIcon=()=>themeBtn.textContent=root.dataset.theme==='dark'?'☀':'☾';setThemeIcon();
  themeBtn.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('nrw_theme',root.dataset.theme);setThemeIcon()});
  document.querySelectorAll('[data-lang-btn]').forEach(btn=>{btn.classList.toggle('active',btn.dataset.langBtn===savedLang);btn.addEventListener('click',()=>{body.dataset.lang=btn.dataset.langBtn;root.lang=btn.dataset.langBtn;localStorage.setItem('nrw_page_lang',btn.dataset.langBtn);document.querySelectorAll('[data-lang-btn]').forEach(x=>x.classList.toggle('active',x===btn));renderDynamic()})});

  const ui={
    de:{locale:'de-DE',today:'HEUTE',tomorrow:'MORGEN',now:'JETZT TUN',details:'Alle wichtigen Hinweise',source:'Quelle',target:'NAP-ZIEL',hardCap:'HARTE LAW-14-GRENZE',limitNote:'Die 3×-Grenze ist keine Empfehlung. Erreiche nur eine lohnende Belohnungsstufe und spare danach für KvK.',noEvents:'Heute liegen noch keine bestätigten Event-Anweisungen vor. Prüfe Discord für kurzfristige NRW-Ansagen.',bearTodayTag:'HEUTE',bearNextTag:'NÄCHSTER TERMIN',bearToday:'Heute ist Bärenfalle. Die nächste findet am {date} statt.',bearNext:'Nächste Bärenfalle: {date}. Danach wieder alle zwei Tage.',genNowTag:'JETZT VERFÜGBAR',confirmed:'INGAME BESTÄTIGT',predicted:'VORAUSSICHTLICH',manual:'NRW-ANLEITUNG'},
    en:{locale:'en-GB',today:'TODAY',tomorrow:'TOMORROW',now:'DO THIS NOW',details:'All important notes',source:'Source',target:'NAP TARGET',hardCap:'HARD LAW 14 LIMIT',limitNote:'The 3× limit is not a recommendation. Reach only a worthwhile reward tier, then save for KvK.',noEvents:'There are no confirmed event instructions for today yet. Check Discord for last-minute NRW calls.',bearTodayTag:'TODAY',bearNextTag:'NEXT DATE',bearToday:'Bear Trap is today. The next one is on {date}.',bearNext:'Next Bear Trap: {date}. Then again every two days.',genNowTag:'AVAILABLE NOW',confirmed:'CONFIRMED IN GAME',predicted:'EXPECTED',manual:'NRW GUIDE'},
    fr:{locale:'fr-FR',today:"AUJOURD’HUI",tomorrow:'DEMAIN',now:'À FAIRE MAINTENANT',details:'Toutes les consignes importantes',source:'Source',target:'OBJECTIF NAP',hardCap:'LIMITE STRICTE LAW 14',limitNote:'La limite de 3× n’est pas une recommandation. Atteins seulement un palier rentable, puis économise pour le KvK.',noEvents:"Aucune consigne d’événement confirmée aujourd’hui. Consulte Discord pour les annonces NRW de dernière minute.",bearTodayTag:"AUJOURD’HUI",bearNextTag:'PROCHAINE DATE',bearToday:'Le Piège à ours a lieu aujourd’hui. Le prochain sera le {date}.',bearNext:'Prochain Piège à ours : {date}. Puis tous les deux jours.',genNowTag:'DISPONIBLE',confirmed:'CONFIRMÉ EN JEU',predicted:'PRÉVU',manual:'GUIDE NRW'}
  };
  const anchor=Date.UTC(2026,8,13),serverOpened=Date.UTC(2025,8,21),kvkCycle=28*day,kvkPrepDuration=5*day+22*3600000,kvkPrepBase=Date.UTC(2026,9,5),releaseDay='2026-09-14';
  const dateKey=d=>d.toISOString().slice(0,10);
  const safe=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const localized=(value,lang)=>typeof value==='string'?value:(value?.[lang]||value?.en||'');
  const eventIcon=e=>e.iconUrl?`<img class="event-icon" src="${safe(e.iconUrl)}" alt="">`:`<span>${safe(e.icon||'📅')}</span>`;
  const isRelease=e=>e.display==='timeline-only'||['new-master-2026-09-14','isnor-master-2026-09-14','hero-generation-6-1044'].includes(e.id);
  const eventsFor=date=>eventFeed.filter(e=>!isRelease(e)&&e.start<=date&&(!e.end||e.end>=date));
  const isBearDay=d=>Math.round((Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-anchor)/day)%2===0;
  const num=value=>new Intl.NumberFormat('de-DE').format(value);
  function eventKind(e){const value=`${e.id||''} ${localized(e.name,'en')}`.toLowerCase();if(value.includes('alliance-brawl')||value.includes('alliance brawl'))return'brawl';if(value.includes('fishing')||value.includes('fischer'))return'fishing';if(value.includes('viking'))return'viking';if(value.includes('eternity'))return'eternity';if(value.includes('cesare'))return'cesare';if(value.includes('golden-glaives')||value.includes('golden glaives'))return'golden';if(value.includes('kill-event')||value.includes('kill event'))return'kill';if(value.includes('armament'))return'armament';return'generic'}

  const brawlCopy={
    de:[
      ['Trucks und Sammeln',['Nutze deine Trucks.','Lass vorbereitete Sammler erst nach dem Reset zurückkehren.','Setze den Bison ein, sobald deine Truppen aktiv sammeln.'],['Andere KvK-intensive Aufgaben heute auslassen.']],
      ['Trucks und Geheimdienstmissionen',['Nutze deine Trucks.','Schließe die Geheimdienstmissionen für die heutige Phase ab.'],['Truppen, Ausbauressourcen und Sammelabschlüsse für ihre passenden Tage aufsparen.']],
      ['Trucks und Sammeln',['Nutze deine Trucks.','Plane lange Sammler vor dem Reset und lass sie heute zurückkehren.','Aktiviere den Bison, sobald die Märsche aktiv sammeln.'],['Andere KvK-intensive Aufgaben heute auslassen.']],
      ['Trucks, Truppenausbildung und Geheimdienstmissionen',['Nutze deine Trucks und Geheimdienstmissionen.','Lass vorbereitete lange Trainingspakete heute fertig werden.'],['Nur bis zur lohnenden Belohnungsstufe spielen und weitere Speedups für KvK sparen.']],
      ['Trucks sowie Bestien und Terrors',['Nutze deine Trucks.','Jage Bestien und Terrors für die heutige Phase.'],['Keine KvK-Ausbauressourcen nur für zusätzliche Brawl-Punkte einsetzen.']],
      ['Trucks sowie Bestien und Terrors',['Nutze deine Trucks.','Jage Bestien und Terrors für die heutige Phase.'],['Keine KvK-Ausbauressourcen nur für zusätzliche Brawl-Punkte einsetzen.']]
    ],
    en:[
      ['Trucks and gathering',['Use your trucks.','Let prepared gathering marches return only after reset.','Activate Bison as soon as your troops are actively gathering.'],['Skip other KvK-intensive tasks today.']],
      ['Trucks and Intel Missions',['Use your trucks.','Complete Intel Missions for today’s stage.'],['Save troops, upgrades and gathering completions for their scoring days.']],
      ['Trucks and gathering',['Use your trucks.','Prepare long gathering marches before reset and let them return today.','Activate Bison as soon as the marches are actively gathering.'],['Skip other KvK-intensive tasks today.']],
      ['Trucks, troop training and Intel Missions',['Use your trucks and Intel Missions.','Finish prepared long troop-training batches today.'],['Stop at a worthwhile reward tier and save further speedups for KvK.']],
      ['Trucks plus beasts and terrors',['Use your trucks.','Hunt beasts and terrors for today’s stage.'],['Do not spend KvK upgrade resources only for extra Brawl points.']],
      ['Trucks plus beasts and terrors',['Use your trucks.','Hunt beasts and terrors for today’s stage.'],['Do not spend KvK upgrade resources only for extra Brawl points.']]
    ],
    fr:[
      ['Camions et collecte',['Utilise tes camions.','Laisse revenir les marches de collecte préparées seulement après le reset.','Active le Bison dès que tes troupes collectent activement.'],['Évite aujourd’hui les autres tâches coûteuses en ressources KvK.']],
      ['Camions et missions de renseignement',['Utilise tes camions.','Termine les missions de renseignement de la phase du jour.'],['Garde troupes, améliorations et collectes pour les jours correspondants.']],
      ['Camions et collecte',['Utilise tes camions.','Prépare de longues collectes avant le reset et laisse-les revenir aujourd’hui.','Active le Bison dès que les marches collectent activement.'],['Évite aujourd’hui les autres tâches coûteuses en ressources KvK.']],
      ['Camions, entraînement et missions de renseignement',['Utilise tes camions et missions de renseignement.','Termine aujourd’hui les longs entraînements préparés.'],['Arrête-toi à un palier rentable et garde les accélérateurs restants pour le KvK.']],
      ['Camions, bêtes et terreurs',['Utilise tes camions.','Chasse les bêtes et les terreurs pour la phase du jour.'],['Ne dépense pas de ressources d’amélioration KvK uniquement pour des points supplémentaires.']],
      ['Camions, bêtes et terreurs',['Utilise tes camions.','Chasse les bêtes et les terreurs pour la phase du jour.'],['Ne dépense pas de ressources d’amélioration KvK uniquement pour des points supplémentaires.']]
    ]
  };
  function brawlPlan(e,date,lang){const phase=Math.floor((new Date(`${date}T00:00:00Z`)-new Date(`${e.start}T00:00:00Z`))/day)+1;if(phase<1||phase>6)return null;const [points,steps,details]=brawlCopy[lang][phase-1],target=phase<=4?125000:187500;return{points,steps,details,phase,limits:{target,hardCap:target*3}}}

  const guides={
    fishing:{
      de:{steps:['Verbessere zuerst die Leine, danach den Haken und zuletzt das Gewicht.','Priorisiere leuchtende Fische und Gegenstände für zusätzliche Münzen.','Nutze Pause → Rückzug, wenn du mit einem Fang nicht zufrieden bist; das Ticket bleibt erhalten.'],details:['Jede Tiefe besitzt eigene Fische. Schwimmt ein Fisch nach rechts, weiche links aus.','Der Schwanz ist ungefährlich; gefangen wird über Fischmaul, Taucherkopf oder Gegenstandsmitte.','In der Dunkelheit den Haken an eine Seite bewegen und bei einem Treffer neu starten.','Spezialgegenstände bleiben nach dem Turnier erhalten – als F2P für spätere Turniere sparen.']},
      en:{steps:['Upgrade the line first, then the hook, and the weight last.','Prioritize glowing fish and objects for extra coins.','Use Pause → Retreat if you dislike a catch; the ticket is preserved.'],details:['Each depth has its own fish. If a fish swims right, dodge it on the left.','The tail is safe; the catch trigger is the fish’s mouth, diver’s head or center of an object.','In darkness, move the hook to one side and restart after hooking a fish.','Special items carry over – F2P players can save them for later tournaments.']},
      fr:{steps:["Améliore d’abord la ligne, puis l’hameçon et enfin le poids.","Priorise les poissons et objets lumineux pour obtenir des pièces supplémentaires.","Utilise Pause → Retraite si la prise ne te convient pas ; le ticket est conservé."],details:["Chaque profondeur possède ses propres poissons. S’ils nagent vers la droite, évite-les par la gauche.","La queue est sans danger ; la capture se déclenche à la bouche, à la tête du plongeur ou au centre de l’objet.","Dans l’obscurité, déplace l’hameçon d’un côté et recommence après avoir accroché un poisson.","Les objets spéciaux sont conservés : les joueurs F2P peuvent les garder pour les prochains tournois."]}
    },
    viking:{
      de:{steps:['Schicke alle Truppen als Verstärkung zu anderen Mitgliedern; in deiner Stadt bleiben nur die drei stärksten Helden und keine Truppen.','Lösche das Feuer in deiner Stadt.','Schicke bei Welle 10 und 20 deine Truppen zum Ebenen-HQ.','Heile während des Events nicht.'],details:['Eine Welle ist gewonnen, sobald mindestens 50 % der angreifenden Truppen getötet wurden.','Nach zwei verlorenen Verteidigungen endet der Angriff auf deine Stadt; durch Verstärkungen kannst du weiter punkten.','Wenn du offline bist, schicke vorher alle Truppen zu Verbündeten und vereinbare möglichst eine gegenseitige Verstärkung.']},
      en:{steps:['Send all troops to reinforce other members; keep only your three strongest heroes and no troops in your city.','Extinguish the fire in your city.','Send troops to the Plains HQ for waves 10 and 20.','Do not heal during the event.'],details:['A wave is defended once at least 50% of the attacking troops are killed.','After two failed defences, attacks on your city stop; you can still score by reinforcing allies.','If offline, send all troops to allies beforehand and arrange reciprocal reinforcements if possible.']},
      fr:{steps:["Envoie toutes tes troupes renforcer d’autres membres ; garde seulement tes trois meilleurs héros et aucune troupe en ville.","Éteins l’incendie dans ta ville.","Envoie tes troupes au QG des Plaines aux vagues 10 et 20.","Ne soigne pas pendant l’événement."],details:["Une vague est défendue dès qu’au moins 50 % des troupes ennemies sont éliminées.","Après deux défaites, les attaques contre ta ville cessent ; tu peux continuer à marquer par les renforts.","Si tu es absent, envoie toutes tes troupes chez des alliés et organise si possible un échange de renforts."]}
    },
    eternity:{
      de:{points:'Orichalcum durch Wachen, Adern und Aderausbrüche',steps:['Zoome heraus und suche einen wenig belegten Bereich. Besiege bevorzugt Cäsars Wachen der Stufe 2.','Baue den Fähigkeitenbaum rechts → rechts → links → links → rechts aus.','Ab Fähigkeit 3: Besetze mit einem Marsch jede Minute eine Ader für 5.000 Orichalcum; die übrigen Märsche besiegen Wachen.','Aktiviere Fähigkeit 5 nur beim Aderausbruch und schicke dann alle Märsche zu den Adern.'],details:['Fähigkeit 1: 1.500 Orichalcum je besiegter Cäsar-Wache.','Fähigkeit 2: +25 % Marschgeschwindigkeit.','Fähigkeit 4: +15 % Sammelgeschwindigkeit.','Fähigkeit 5: +66 % Sammelgeschwindigkeit für 60 Sekunden, 5 Minuten Abklingzeit. Währenddessen die Truppen nicht vor Ablauf der fünf Minuten zurückrufen.']},
      en:{points:'Orichalcum from guards, veins and vein outbursts',steps:['Zoom out and find a quiet area. Prioritize level 2 Caesar Guards.','Build the skill tree right → right → left → left → right.','From skill 3: use one march to occupy a vein every minute for 5,000 Orichalcum; keep the other marches on guards.','Activate skill 5 only during a vein outburst, then send all marches to the veins.'],details:['Skill 1: 1,500 Orichalcum per defeated Caesar Guard.','Skill 2: +25% march speed.','Skill 4: +15% gathering speed.','Skill 5: +66% gathering speed for 60 seconds, 5-minute cooldown. Do not recall troops before the five minutes have passed.']},
      fr:{points:"Orichalque grâce aux gardes, filons et éruptions",steps:["Dézoome et choisis une zone peu fréquentée. Priorise les gardes de César de niveau 2.","Améliore l’arbre : droite → droite → gauche → gauche → droite.","Dès la compétence 3 : occupe un filon chaque minute avec une marche pour 5 000 Orichalques ; les autres combattent les gardes.","Active la compétence 5 uniquement pendant une éruption et envoie alors toutes les marches aux filons."],details:["Compétence 1 : 1 500 Orichalques par garde de César vaincu.","Compétence 2 : +25 % de vitesse de marche.","Compétence 4 : +15 % de vitesse de collecte.","Compétence 5 : +66 % de vitesse de collecte pendant 60 secondes, recharge de 5 minutes. Ne rappelle pas les troupes avant la fin des cinq minutes."]}
    },
    cesare:{
      de:{steps:['Greife jeden Captain zunächst mit genau einem Soldaten und ohne Helden an.','Warte, bis alle aktiven Mitglieder einmal getroffen und ihre Teilnahmebelohnung gesichert haben.','Erst danach darf der Captain mit vollständigen Märschen besiegt werden.'],details:['So erhält die gesamte Allianz die maximale Zahl an Teilnahmebelohnungen.']},
      en:{steps:['Attack each Captain first with exactly one troop and no hero.','Wait until all active members have landed one hit and secured participation rewards.','Only then finish the Captain with full marches.'],details:['This maximizes participation rewards for the whole alliance.']},
      fr:{steps:["Attaque d’abord chaque capitaine avec exactement un soldat et sans héros.","Attends que tous les membres actifs aient porté un coup et obtenu la récompense de participation.","Ensuite seulement, termine le capitaine avec des marches complètes."],details:["Cette méthode maximise les récompenses de participation de toute l’alliance."]}
    },
    golden:{
      de:{steps:['00:00 UTC: Missionen abschließen und Belohnungen abholen.','08:00 UTC: Missionen abschließen, Belohnungen nicht abholen.','16:00 UTC: Missionen weder abschließen noch abholen. Danach Pans zusätzliche Geheimdienstmission aktivieren.','Nach dem nächsten Reset die vorbereiteten Missionen abschließen und gesammelt abholen.'],details:['Diese Vorbereitung erzeugt zusätzliche Punkte für die nächste Prephase.']},
      en:{steps:['00:00 UTC: complete missions and claim rewards.','08:00 UTC: complete missions but do not claim rewards.','16:00 UTC: neither complete nor claim missions. Then activate Pan’s extra Intel Mission.','After the next reset, complete and claim the prepared missions.'],details:['This preparation creates extra points for the next pre-phase.']},
      fr:{steps:["00:00 UTC : termine les missions et récupère les récompenses.","08:00 UTC : termine les missions sans récupérer les récompenses.","16:00 UTC : ne termine ni ne récupère les missions. Active ensuite la mission de renseignement supplémentaire de Pan.","Après le reset suivant, termine et récupère les missions préparées."],details:["Cette préparation rapporte des points supplémentaires pour la prochaine préphase."]}
    },
    kill:{
      de:{steps:['Ein Schild ist aufgrund der Servergesetze für NRW-Mitglieder nicht notwendig.','Schicke während des Kill Events keine Sammler auf Ressourcenfelder.','Halte deine Krankenstation frei und beachte die Castle-Battle-Ansagen auf Discord.'],details:['Stadtangriffe sind grundsätzlich verboten. Ausnahmen: allianzlose Städte, Ein-Mitglied-Allianzen und KOK.','Kill-Event-Punkte können während der Castle Battle gesammelt werden. Danach kann wieder sicher gesammelt werden.']},
      en:{steps:['NRW members do not need a shield because of the server laws.','Do not send gatherers to resource tiles during the Kill Event.','Keep your infirmary clear and follow Castle Battle calls on Discord.'],details:['City attacks are prohibited except against cities without an alliance, one-member alliances and KOK.','Kill Event points can be earned during Castle Battle. Gathering is safe again afterwards.']},
      fr:{steps:["Les membres NRW n’ont pas besoin de bouclier grâce aux lois du serveur.","N’envoie aucun collecteur sur les ressources pendant le Kill Event.","Garde ton infirmerie libre et suis les consignes de Castle Battle sur Discord."],details:["Les attaques de villes sont interdites, sauf contre les joueurs sans alliance, les alliances d’un membre et KOK.","Les points du Kill Event peuvent être gagnés pendant la Castle Battle. La collecte redevient sûre ensuite."]}
    }
  };
  function planFromFeed(e,date,lang){const plan=e.dailyPlans?.[date];if(!plan)return null;return{points:localized(plan.points,lang),steps:plan.steps?.[lang]||plan.steps?.en||[],prepare:plan.prepare?{title:localized(plan.prepare.title,lang),steps:plan.prepare.steps?.[lang]||plan.prepare.steps?.en||[]}:null,details:plan.note?[localized(plan.note,lang)]:[],limits:plan.limits||null}}
  function coachFor(e,date,lang){const kind=eventKind(e),manual=kind==='brawl'?brawlPlan(e,date,lang):(guides[kind]?.[lang]||null),feed=planFromFeed(e,date,lang),tips=e.tips?.[lang]||e.tips?.en||[];const chosen=manual||feed||{steps:tips.slice(0,3),details:tips.slice(3)};if(feed&&manual){chosen.prepare=feed.prepare||chosen.prepare;if(feed.points&&!chosen.points)chosen.points=feed.points}return chosen}
  function confidenceLabel(e,lang){const t=ui[lang];if(e.manual)return t.manual;if(e.confidence==='confirmed-ingame'||e.confidence==='official')return t.confirmed;if(e.confidence==='predicted')return t.predicted;return''}
  function eventCard(e,date,lang,status){const t=ui[lang],coach=coachFor(e,date,lang)||{steps:[],details:[]},steps=coach.steps||[],details=coach.details||[],label=confidenceLabel(e,lang);const stepHtml=steps.map((step,index)=>`<li><b>${index+1}</b><span>${safe(step)}</span></li>`).join('');const detailHtml=details.length?`<details><summary>${t.details}</summary><ul>${details.map(x=>`<li>${safe(x)}</li>`).join('')}</ul></details>`:'';const prepHtml=coach.prepare?.steps?.length?`<div class="prepare-box"><strong>${safe(coach.prepare.title)}</strong><p>${safe(coach.prepare.steps.join(' • '))}</p></div>`:'';const scoreHtml=coach.points?`<div class="score-focus"><span>🎯 ${lang==='de'?'HEUTE ZÄHLT':lang==='fr'?"POINTS DU JOUR":'TODAY SCORES'}</span><strong>${safe(coach.points)}</strong></div>`:'';const limits=coach.limits;const limitsHtml=limits?`<div class="law-limit"><div><span>${t.target}</span><strong>${num(limits.target)}</strong></div><i></i><div><span>${t.hardCap}</span><strong>${num(limits.hardCap)}</strong></div><p>${t.limitNote}</p></div>`:'';const source=e.sourceUrl?`<a class="guide-link" href="${safe(e.sourceUrl)}" target="_blank" rel="noopener">${t.source} ↗</a>`:'';return`<article class="event-card"><header><div class="event-card-icon">${eventIcon(e)}</div><div><span class="event-status">${safe(status)}</span><h3>${safe(localized(e.name,lang))}</h3></div>${label?`<span class="verified-badge">${safe(label)}</span>`:''}</header>${scoreHtml}${prepHtml}<div class="action-block"><h4>${t.now}</h4><ol>${stepHtml}</ol></div>${limitsHtml}${detailHtml}${source}</article>`}

  function mythicVirtual(date,lang){const weekday=new Date(`${date}T00:00:00Z`).getUTCDay();const data={de:{name:'Mythische Prüfung',status:'WÖCHENTLICH',ratio:'Infanterie/Kavallerie/Bogenschützen',zones:{col:['Kolosseum','50/10/40'],forest:['Wald des Lebens','50/15/35'],crystal:['Kristallhöhle','60/20/20'],knowledge:['Wissensnetzwerk','50/20/30'],molten:['Schmelzfestung','60/15/25'],radiant:['Strahlender Gipfel','Team 1: 50/20/30. Kavalleriehelden der Teams tauschen; Team 2: 50/35/15.']}},en:{name:'Mythic Trial',status:'WEEKLY',ratio:'Infantry/Cavalry/Archers',zones:{col:['Colosseum','50/10/40'],forest:['Forest of Life','50/15/35'],crystal:['Crystal Cave','60/20/20'],knowledge:['Knowledge Network','50/20/30'],molten:['Molten Fort','60/15/25'],radiant:['Radiant Peak','Team 1: 50/20/30. Swap the cavalry heroes between teams; Team 2: 50/35/15.']}},fr:{name:'Épreuve mythique',status:'HEBDOMADAIRE',ratio:'Infanterie/Cavalerie/Archers',zones:{col:['Colisée','50/10/40'],forest:['Forêt de la vie','50/15/35'],crystal:['Grotte de cristal','60/20/20'],knowledge:['Réseau du savoir','50/20/30'],molten:['Forteresse en fusion','60/15/25'],radiant:['Pic radieux','Équipe 1 : 50/20/30. Échange les héros de cavalerie ; équipe 2 : 50/35/15.']}}}[lang];const keys=weekday===0?['radiant']:(weekday<=2?['col']:(weekday<=4?['forest','crystal']:['knowledge','molten']));return{id:`mythic-${date}`,icon:'🔮',manual:true,name:{[lang]:data.name},virtualCoach:{steps:keys.map(k=>`${data.zones[k][0]}: ${data.zones[k][1]} · ${data.ratio}`),details:[lang==='de'?'Formation vor dem Start kontrollieren; die Werte sind NRW-Ausgangsformationen.':lang==='fr'?"Contrôle la formation avant le départ ; ces valeurs sont les formations de départ NRW.":'Check the formation before starting; these are NRW starting formations.']},virtualStatus:data.status}}
  function championshipVirtual(date,lang){const weekday=new Date(`${date}T00:00:00Z`).getUTCDay();if(weekday!==1&&weekday!==2)return null;const data={de:{name:'Allianzmeisterschaft · Anmeldung',steps:['Aktiviere deine Pet-Buffs vor der Anmeldung.','Ab 250 Mio. Spielerkraft: 60/40/0 mit defensiven Helden; tausche bei Bedarf die beste Ausrüstung.','Unter 250 Mio. Spielerkraft: 50/20/30 mit deinen drei besten Helden.','Melde dich ausschließlich in der mittleren Reihe an.'],status:'ANMELDUNG OFFEN'},en:{name:'Alliance Championship · Registration',steps:['Activate your Pet Buffs before registering.','At 250M power or above: 60/40/0 with defensive heroes; move your best gear if needed.','Below 250M power: 50/20/30 with your three best heroes.','Register only in the middle lane.'],status:'REGISTRATION OPEN'},fr:{name:'Championnat d’alliance · Inscription',steps:["Active tes bonus de familier avant l’inscription.","À partir de 250 M de puissance : 60/40/0 avec des héros défensifs ; transfère le meilleur équipement si nécessaire.","Sous 250 M de puissance : 50/20/30 avec tes trois meilleurs héros.","Inscris-toi uniquement dans la ligne centrale."],status:'INSCRIPTION OUVERTE'}}[lang];return{id:`championship-${date}`,icon:'🏆',manual:true,name:{[lang]:data.name},virtualCoach:{steps:data.steps,details:[]},virtualStatus:data.status}}
  function virtualCard(e,lang){const t=ui[lang],steps=e.virtualCoach.steps.map((step,index)=>`<li><b>${index+1}</b><span>${safe(step)}</span></li>`).join(''),details=e.virtualCoach.details.length?`<details><summary>${t.details}</summary><ul>${e.virtualCoach.details.map(x=>`<li>${safe(x)}</li>`).join('')}</ul></details>`:'';return`<article class="event-card"><header><div class="event-card-icon"><span>${e.icon}</span></div><div><span class="event-status">${safe(e.virtualStatus)}</span><h3>${safe(localized(e.name,lang))}</h3></div><span class="verified-badge">${t.manual}</span></header><div class="action-block"><h4>${t.now}</h4><ol>${steps}</ol></div>${details}</article>`}
  function cardsFor(date,lang,status){const cards=eventsFor(date).map(e=>eventCard(e,date,lang,status)),virtual=[championshipVirtual(date,lang),mythicVirtual(date,lang)].filter(Boolean);return cards.concat(virtual.map(e=>virtualCard(e,lang)))}
  function kvkPrepWindow(now){let start=kvkPrepBase;while(now.getTime()>=start+kvkPrepDuration)start+=kvkCycle;return{start:new Date(start),active:now.getTime()>=start}}
  function nextBearAt(hour,minute){const now=new Date();for(let add=0;add<4;add++){const x=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+add,hour,minute));if(isBearDay(x)&&x>now)return x}return new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+2,hour,minute))}
  function fmtCountdown(target){let s=Math.max(0,Math.floor((target-Date.now())/1000)),days=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return(days?days+'d ':'')+[h,m,sec].map(v=>String(v).padStart(2,'0')).join(':')}
  function placeReleaseCard(today){const card=document.getElementById('gen6Card'),priority=document.getElementById('priorityGrid'),lower=document.getElementById('releaseLower'),section=document.getElementById('releaseDetails'),released=today>releaseDay;if(released&&card.parentElement!==lower)lower.appendChild(card);if(!released&&card.parentElement!==priority)priority.appendChild(card);section.hidden=!released;priority.classList.toggle('single',released)}
  function renderDynamic(){const lang=body.dataset.lang||'en',t=ui[lang],now=new Date(),todayUTC=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())),tomorrow=new Date(todayUTC.getTime()+day),today=dateKey(todayUTC),next=dateKey(tomorrow),locale=t.locale;document.getElementById('weekday').textContent=now.toLocaleDateString(locale,{weekday:'long',timeZone:'UTC'});document.getElementById('dateLabel').textContent=now.toLocaleDateString(locale,{day:'2-digit',month:'short',timeZone:'UTC'}).toUpperCase();const kvk=kvkPrepWindow(now);document.getElementById('kvkStartLabel').textContent=kvk.start.toLocaleDateString(locale,{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).toUpperCase()+' · 00:00 UTC';const serverAge=Math.floor((todayUTC.getTime()-serverOpened)/day);document.querySelectorAll('[data-server-age]').forEach(el=>el.textContent=serverAge);placeReleaseCard(today);const todayCards=cardsFor(today,lang,t.today);document.getElementById('todayEvents').innerHTML=todayCards.length?todayCards.join(''):`<div class="empty-plan">${t.noEvents}</div>`;document.getElementById('tomorrowTitle').textContent=tomorrow.toLocaleDateString(locale,{weekday:'long',day:'2-digit',month:'2-digit',timeZone:'UTC'});document.getElementById('tomorrowTasks').innerHTML=cardsFor(next,lang,t.tomorrow).join('');const todayTrapEnd=new Date(todayUTC.getTime()+18.5*3600000),nextDay=nextBearAt(17,0),dateFmt=d=>d.toLocaleDateString(locale,{weekday:'long',day:'2-digit',month:'2-digit',timeZone:'UTC'}),followingBear=isBearDay(todayUTC)&&now<todayTrapEnd?new Date(todayUTC.getTime()+2*day):nextDay;document.getElementById('bearTag').textContent=isBearDay(todayUTC)&&now<todayTrapEnd?t.bearTodayTag:t.bearNextTag;document.getElementById('genTag').textContent=t.genNowTag;document.getElementById('bearDateNote').textContent=(isBearDay(todayUTC)&&now<todayTrapEnd?t.bearToday:t.bearNext).replace('{date}',dateFmt(followingBear))}
  function tick(){const now=new Date(),lang=body.dataset.lang||'en',kvk=kvkPrepWindow(now);document.getElementById('utcClock').textContent=now.toLocaleTimeString('en-GB',{hour12:false,timeZone:'UTC'});document.getElementById('kvkPrepCountdown').textContent=kvk.active?({de:'PREP LÄUFT',en:'PREP ACTIVE',fr:'PREP EN COURS'}[lang]||'PREP ACTIVE'):fmtCountdown(kvk.start);document.getElementById('bt1Countdown').textContent=fmtCountdown(nextBearAt(17,0));document.getElementById('bt2Countdown').textContent=fmtCountdown(nextBearAt(18,30));document.getElementById('gen6Countdown').textContent={de:'Freigeschaltet',en:'Unlocked',fr:'Débloqué'}[lang]||'Unlocked';document.querySelectorAll('[data-count-to]').forEach(el=>{const d=new Date(el.dataset.countTo);el.textContent=d>now?fmtCountdown(d):({de:'Jetzt verfügbar',en:'Available now',fr:'Disponible'}[lang]||'Available now')})}

  const profileKey='nrw_member_profile_v1',playerNameInput=document.getElementById('playerName'),playerIdInput=document.getElementById('playerId');try{const p=JSON.parse(localStorage.getItem(profileKey)||'null');if(p){playerNameInput.value=p.playerName||'';playerIdInput.value=p.playerId||'';document.querySelectorAll('#languageGrid input').forEach(i=>i.checked=(p.languages||[]).includes(i.value))}}catch(e){}
  const messages={de:{missing:'Bitte Name, Player ID und Sprache angeben.',invalid:'Die Player ID darf nur Zahlen enthalten.',saved:'Im NRW-Spielerprofil gespeichert ✓',queued:'Zur Prüfung gespeichert ✓',error:'Speichern gerade nicht möglich.'},en:{missing:'Please add name, Player ID and language.',invalid:'Player ID must contain numbers only.',saved:'Saved to your NRW member profile ✓',queued:'Saved for review ✓',error:'Could not save right now.'},fr:{missing:'Ajoute ton nom, Player ID et ta langue.',invalid:'La Player ID doit contenir uniquement des chiffres.',saved:'Enregistré dans ton profil NRW ✓',queued:'Enregistré pour vérification ✓',error:'Enregistrement impossible.'}};
  document.getElementById('saveProfile').addEventListener('click',async()=>{const lang=body.dataset.lang||'en',m=messages[lang],status=document.getElementById('saveStatus'),button=document.getElementById('saveProfile'),profile={schemaVersion:2,playerName:playerNameInput.value.trim(),playerId:playerIdInput.value.trim(),languages:[...document.querySelectorAll('#languageGrid input:checked')].map(i=>i.value),otherLanguage:'',source:'nrw-player-dashboard',updatedAt:new Date().toISOString()};status.className='';if(!profile.playerName||!profile.playerId||!profile.languages.length){status.textContent=m.missing;status.className='error';return}if(!/^\d+$/.test(profile.playerId)){status.textContent=m.invalid;status.className='error';return}button.disabled=true;try{const r=await fetch('https://bdzlgirowutasrsycjfj.supabase.co/functions/v1/nrw-welcome-language',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)}),data=await r.json().catch(()=>({}));if(!r.ok||!data.ok)throw new Error();localStorage.setItem(profileKey,JSON.stringify(profile));status.textContent=data.queued?m.queued:m.saved;status.className='success'}catch(e){status.textContent=m.error;status.className='error'}finally{button.disabled=false}});
  fetch('/dashboard/events.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(data=>{eventFeed=Array.isArray(data.events)?data.events:[];renderDynamic()}).catch(()=>renderDynamic());
  renderDynamic();tick();setInterval(tick,1000);setInterval(renderDynamic,60000);
})();
