(function(){
  const body=document.body,root=document.documentElement,day=86400000;
  let eventFeed=[],eventGuideDb={events:[],catalogOnly:[],sources:{}},expandedCards=new Set();
  const savedLang=localStorage.getItem('nrw_page_lang')||'en';
  const savedTheme=localStorage.getItem('nrw_theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
  body.dataset.lang=savedLang;root.lang=savedLang;root.dataset.theme=savedTheme;
  const themeBtn=document.getElementById('themeBtn');
  const setThemeIcon=()=>themeBtn.textContent=root.dataset.theme==='dark'?'☀':'☾';setThemeIcon();
  themeBtn.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('nrw_theme',root.dataset.theme);setThemeIcon()});
  document.querySelectorAll('[data-lang-btn]').forEach(btn=>{btn.classList.toggle('active',btn.dataset.langBtn===savedLang);btn.addEventListener('click',()=>{body.dataset.lang=btn.dataset.langBtn;root.lang=btn.dataset.langBtn;localStorage.setItem('nrw_page_lang',btn.dataset.langBtn);document.querySelectorAll('[data-lang-btn]').forEach(x=>x.classList.toggle('active',x===btn));renderDynamic()})});

  const ui={
    de:{locale:'de-DE',today:'HEUTE',tomorrow:'MORGEN',now:'JETZT TUN',details:'Alle wichtigen Hinweise',open:'Öffnen',close:'Schließen',source:'Quelle',target:'NAP-ZIEL',hardCap:'HARTE LAW-14-GRENZE',limitNote:'Die 3×-Grenze ist keine Empfehlung. Erreiche nur eine lohnende Belohnungsstufe und spare danach für KvK.',noEvents:'Heute liegen noch keine bestätigten Event-Anweisungen vor. Prüfe Discord für kurzfristige NRW-Ansagen.',bearTodayTag:'HEUTE',bearNextTag:'NÄCHSTER TERMIN',bearToday:'Heute ist Bärenfalle. Die nächste findet am {date} statt.',bearNext:'Nächste Bärenfalle: {date}. Danach wieder alle zwei Tage.',genNowTag:'JETZT VERFÜGBAR',confirmed:'OFFIZIELLER RHYTHMUS',predicted:'VORAUSSICHTLICH',rhythm:'OFFIZIELLER RHYTHMUS',manual:'NRW-TIPP',why:'WARUM?',important:'JETZT WICHTIG'},
    en:{locale:'en-GB',today:'TODAY',tomorrow:'TOMORROW',now:'DO THIS NOW',details:'All important notes',open:'Open',close:'Close',source:'Source',target:'NAP TARGET',hardCap:'HARD LAW 14 LIMIT',limitNote:'The 3× limit is not a recommendation. Reach only a worthwhile reward tier, then save for KvK.',noEvents:'There are no confirmed event instructions for today yet. Check Discord for last-minute NRW calls.',bearTodayTag:'TODAY',bearNextTag:'NEXT DATE',bearToday:'Bear Trap is today. The next one is on {date}.',bearNext:'Next Bear Trap: {date}. Then again every two days.',genNowTag:'AVAILABLE NOW',confirmed:'OFFICIAL SCHEDULE',predicted:'EXPECTED',rhythm:'OFFICIAL SCHEDULE',manual:'NRW TIP',why:'WHY?',important:'IMPORTANT NOW'},
    fr:{locale:'fr-FR',today:"AUJOURD’HUI",tomorrow:'DEMAIN',now:'À FAIRE MAINTENANT',details:'Toutes les consignes importantes',open:'Ouvrir',close:'Fermer',source:'Source',target:'OBJECTIF NAP',hardCap:'LIMITE STRICTE LAW 14',limitNote:'La limite de 3× n’est pas une recommandation. Atteins seulement un palier rentable, puis économise pour le KvK.',noEvents:"Aucune consigne d’événement confirmée aujourd’hui. Consulte Discord pour les annonces NRW de dernière minute.",bearTodayTag:"AUJOURD’HUI",bearNextTag:'PROCHAINE DATE',bearToday:'Le Piège à ours a lieu aujourd’hui. Le prochain sera le {date}.',bearNext:'Prochain Piège à ours : {date}. Puis tous les deux jours.',genNowTag:'DISPONIBLE',confirmed:'CALENDRIER OFFICIEL',predicted:'PRÉVU',rhythm:'CALENDRIER OFFICIEL',manual:'CONSEIL NRW',why:'POURQUOI ?',important:'IMPORTANT MAINTENANT'}
  };
  const anchor=Date.UTC(2026,8,13),serverOpened=Date.UTC(2025,8,21),kvkCycle=28*day,kvkPrepDuration=5*day+22*3600000,kvkPrepBase=Date.UTC(2026,9,5),releaseDay='2026-09-14';
  const dateKey=d=>d.toISOString().slice(0,10);
  const safe=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const localized=(value,lang)=>typeof value==='string'?value:(value?.[lang]||value?.en||'');
  const eventIcon=e=>e.iconUrl?`<img class="event-icon${e.iconFit==='cover'?' event-icon-cover':''}" src="${safe(e.iconUrl)}" alt="">`:`<span>${safe(e.icon||'📅')}</span>`;
  const isRelease=e=>e.display==='timeline-only'||['new-master-2026-09-14','isnor-master-2026-09-14','hero-generation-6-1044'].includes(e.id);
  const eventsFor=date=>{const listed=eventFeed.filter(e=>!isRelease(e)&&!guideSuppresses(e)&&e.start<=date&&(!e.end||e.end>=date)),kinds=new Set(listed.map(eventKind));return listed.concat(officialRhythmFor(date).filter(e=>!guideSuppresses(e)&&!kinds.has(eventKind(e))))};
  const isBearDay=d=>Math.round((Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-anchor)/day)%2===0;
  const num=value=>new Intl.NumberFormat('de-DE').format(value);
  function eventKind(e){const value=`${e.id||''} ${localized(e.name,'en')}`.toLowerCase();if(value.includes('alliance-brawl')||value.includes('alliance brawl'))return'brawl';if(value.includes('kingdom-of-power')||value.includes('kvk'))return'kvk';if(value.includes('strongest-governor')||value.includes('strongest governor'))return'strongest';if(value.includes('fishing')||value.includes('fischer'))return'fishing';if(value.includes('viking'))return'viking';if(value.includes('eternity'))return'eternity';if(value.includes('cesare'))return'cesare';if(value.includes('golden-glaives')||value.includes('golden glaives'))return'golden';if(value.includes('kill-event')||value.includes('kill event'))return'kill';if(value.includes('officer-project')||value.includes('officer project'))return'officer';if(value.includes('armament'))return'armament';if(value.includes('merchant empire')||value.includes('handelsimperium')||value.includes('empire commercial'))return'merchant';if(value.includes('alliance-championship')||value.includes('alliance championship'))return'championship';if(value.includes('bear-trap')||value.includes('bear trap'))return'bear';if(value.includes('champagne'))return'champagne';if(value.includes('roulette'))return'roulette';if(value.includes('transfer'))return'transfer';return'generic'}
  const guideIdByKind={brawl:'alliance-brawl',kvk:'kingdom-of-power-prep',strongest:'strongest-governor',armament:'armament-competition',officer:'officer-project',golden:'golden-glaives',merchant:'merchant-empire',fishing:'fishing-tournament',viking:'viking-vengeance',eternity:'eternitys-reach',cesare:'cesares-fury',championship:'alliance-championship',kill:'kill-event',bear:'bear-trap',transfer:'kingdom-transfer',champagne:'champagne-fair',roulette:'hero-roulette'};
  const normGuideName=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,' ').trim().toLowerCase();
  function guideRecordFor(e){const detailed=eventGuideDb.events||[],id=String(e.id||''),direct=detailed.find(g=>id===g.id||id.startsWith(`${g.id}-`));if(direct)return direct;const mapped=guideIdByKind[eventKind(e)];if(mapped){const hit=detailed.find(g=>g.id===mapped);if(hit)return hit}const eventName=normGuideName(localized(e.name,'en')).split(' type ')[0].split(' 20')[0];return(eventGuideDb.catalogOnly||[]).find(g=>{const name=normGuideName(g.name);return eventName===name||eventName.startsWith(name+' ')})||null}
  function guideSuppresses(e){const guide=guideRecordFor(e),eligibility=guide?.dashboardEligible||'';return eligibility.startsWith('no-')}
  function guideSourceFor(e){const guide=guideRecordFor(e);if(!guide)return'';if(guide.sourceUrl)return guide.sourceUrl;for(const key of guide.sources||[]){const source=eventGuideDb.sources?.[key];if(source?.url)return source.url}return''}
  function knowledgeCoachFor(e,lang){const guide=guideRecordFor(e);if(!guide||guideSuppresses(e)||guide.staticStrategy===false)return null;const steps=Array.isArray(guide.nrwGuide?.[lang])?guide.nrwGuide[lang]:Array.isArray(guide.nrwGuide?.en)?guide.nrwGuide.en:[],details=[],objective=localized(guide.objective,lang),rule=localized(guide.nrwRule,lang);if(objective)details.push(objective);if(rule)details.push(rule);if(typeof guide.mechanic==='string'&&lang==='en')details.push(guide.mechanic);return{steps,details}}


  function rhythmEvent(kind,type,start){
    const isArmament=kind==='armament',typeOne=type===1,sourceUrl=isArmament?'https://kingshotdata.com/events/armament-competition/':'https://kingshotdata.com/events/officer-project-event/',iconUrl=isArmament?'https://kingshotdata.com/uploads/2025/04/city-development-event-icon.webp':'https://kingshotdata.com/uploads/2025/03/power-up-event-icon.webp';
    const copy=isArmament?(typeOne?{
      name:{de:'Rüstungswettbewerb · Typ 1',en:'Armament Competition · Type 1',fr:'Compétition d’armement · Type 1'},
      points:{de:'Gouverneursausrüstung, Truegold, Heldensplitter, Meistermaterialien und Speedups',en:'Governor Gear, Truegold, Hero Shards, Master materials and Speedups',fr:'Équipement du gouverneur, Or véritable, fragments de héros, matériaux de Maître et accélérateurs'},
      reward:{de:'Abschlussbelohnung: Visionen des Kunsthandwerkers',en:"Final milestone reward: Artisan’s Visions",fr:"Récompense finale : Visions d’artisan"}
    }:{
      name:{de:'Rüstungswettbewerb · Typ 2 (Truegold)',en:'Armament Competition · Type 2 (Truegold)',fr:'Compétition d’armement · Type 2 (Or véritable)'},
      points:{de:'Truegold, Gouverneursausrüstung, Schmiedehämmer, Mithril, Widgets und Speedups',en:'Truegold, Governor Gear, Forgehammers, Mithril, Widgets and Speedups',fr:'Or véritable, équipement du gouverneur, marteaux, mithril, widgets et accélérateurs'},
      reward:{de:'Abschlussbelohnung: Truegold',en:'Final milestone reward: Truegold',fr:'Récompense finale : Or véritable'}
    }):(typeOne?{
      name:{de:'Offiziersprojekt · Typ 1',en:'Officer Project · Type 1',fr:"Projet d’officier · Type 1"},
      points:{de:'Gouverneursamulette, Schmiedehämmer, Mithril, Widgets und Truppenausbildung',en:'Governor Charms, Forgehammers, Mithril, Widgets and troop training',fr:'Charmes du gouverneur, marteaux, mithril, widgets et entraînement'},
      reward:{de:'Abschlussbelohnung: Schmiedehämmer',en:'Final milestone reward: Forgehammers',fr:'Récompense finale : marteaux de forge'}
    }:{
      name:{de:'Offiziersprojekt · Typ 2',en:'Officer Project · Type 2',fr:"Projet d’officier · Type 2"},
      points:{de:'Gouverneursausrüstung, Heldensplitter, Schmiedehämmer und Widgets',en:'Governor Gear, Hero Shards, Forgehammers and Widgets',fr:'Équipement du gouverneur, fragments de héros, marteaux et widgets'},
      reward:{de:'Abschlussbelohnung: Amulettdesigns',en:'Final milestone reward: Charm Designs',fr:'Récompense finale : plans de charme'}
    });
    const steps={
      de:isArmament?['Das Event kann ausgelassen werden – verbrauche keine KvK-Ressourcen nur für diese Belohnungen.','Spiele nur eine lohnende Belohnungsstufe, wenn NRW dafür ein konkretes Ziel veröffentlicht.','Die 3×-Grenze ist strikt. Ohne veröffentlichten Punktwert keine Ressourcen auf Verdacht einsetzen.']:['Prüfe vor dem Einsatz, ob sich die aktuelle Belohnungsstufe für deine Ressourcen lohnt.','Kombiniere Punktequellen nur mit einem passenden Allianzgemenge- oder KvK-Tag.','Die 3×-Grenze für KvK-Ressourcen bleibt eine strikte Obergrenze.'],
      en:isArmament?['This event can be skipped – do not spend KvK resources only for these rewards.','Play only to a worthwhile reward tier if NRW publishes a specific target.','The 3× limit is strict. Do not spend resources speculatively without a published point limit.']:['Check whether the current reward tier is worth your resources before spending.','Combine scoring sources only with a matching Alliance Brawl or KvK day.','The 3× limit for KvK resources remains a strict upper limit.'],
      fr:isArmament?["Cet événement peut être ignoré : ne dépense pas de ressources KvK uniquement pour ces récompenses.","Joue seulement jusqu’à un palier rentable si NRW publie un objectif précis.","La limite de 3× est stricte. Sans valeur publiée, ne dépense aucune ressource au hasard."]:["Vérifie que le palier de récompense vaut tes ressources avant de les dépenser.","Combine les sources de points uniquement avec un jour correspondant d’Alliance Brawl ou de KvK.","La limite de 3× pour les ressources KvK reste une limite supérieure stricte."]
    };
    const eventLimits=isArmament
      ?{target:typeOne?20000:38000,hardCap:typeOne?60000:114000,note:{
        de:typeOne?'60.000 Punkte sind die strikte 3×-Grenze. Genau 60.000 sind noch erlaubt; erst darüber zählt es als Law-14-Verstoß. Die Grenze ist keine Empfehlung.':'114.000 Punkte sind die strikte 3×-Grenze. Genau 114.000 sind noch erlaubt; erst darüber zählt es als Law-14-Verstoß. Die Grenze ist keine Empfehlung.',
        en:typeOne?'60,000 points is the strict 3× limit. Exactly 60,000 is still allowed; only scores above it count as a Law 14 violation. The limit is not a recommendation.':'114,000 points is the strict 3× limit. Exactly 114,000 is still allowed; only scores above it count as a Law 14 violation. The limit is not a recommendation.',
        fr:typeOne?'60 000 points constituent la limite stricte de 3×. Exactement 60 000 reste autorisé ; seule une valeur supérieure compte comme infraction à la Law 14. Cette limite n’est pas une recommandation.':'114 000 points constituent la limite stricte de 3×. Exactement 114 000 reste autorisé ; seule une valeur supérieure compte comme infraction à la Law 14. Cette limite n’est pas une recommandation.'
      }}
      :{target:typeOne?310000:453000,hardCap:typeOne?930000:1359000,note:{de:'Die 3×-Grenze ist keine Empfehlung. Erreiche nur eine lohnende Belohnungsstufe oder lasse das Event aus und spare danach für KvK.',en:'The 3× limit is not a recommendation. Reach only a worthwhile reward tier or skip the event, then save for KvK.',fr:"La limite de 3× n’est pas une recommandation. Atteins seulement un palier rentable ou ignore l’événement, puis économise pour le KvK."}};
    return{id:`rhythm-${kind}-${start}`,start,end:dateKey(new Date(new Date(`${start}T00:00:00Z`).getTime()+day)),iconUrl,confidence:'public-timeline',name:copy.name,sourceUrl,rhythmCoach:{de:{points:copy.points.de,steps:steps.de,details:[copy.reward.de],limits:eventLimits},en:{points:copy.points.en,steps:steps.en,details:[copy.reward.en],limits:eventLimits},fr:{points:copy.points.fr,steps:steps.fr,details:[copy.reward.fr],limits:eventLimits}}};
  }
  function officialRhythmFor(date){
    const d=new Date(`${date}T00:00:00Z`),cycleAnchor=Date.UTC(2026,8,14),elapsed=Math.floor((d.getTime()-cycleAnchor)/day),cycleDay=((elapsed%28)+28)%28,cycleStart=d.getTime()-cycleDay*day;
    const slots=[
      {from:0,to:1,kind:'armament',type:1},
      {from:2,to:3,kind:'officer',type:1},
      {from:4,to:5,kind:'armament',type:2},
      {from:6,to:7,kind:'officer',type:2}
    ];
    return slots.filter(slot=>cycleDay>=slot.from&&cycleDay<=slot.to).map(slot=>rhythmEvent(slot.kind,slot.type,dateKey(new Date(cycleStart+slot.from*day))))
  }

  const brawlCopy={
    de:[
      ['Trucks und Sammeln',['Nutze deine Trucks.','Lass die vor dem Reset gestarteten Sammler erst nach dem Reset zurückkehren – erst dann zählen die gesammelten Ressourcen.','Schicke danach einen neuen Sammelmarsch los. Die vor dem Reset aktivierte Bison-Fähigkeit wird sofort ausgelöst und der Marsch kehrt direkt vollständig gesammelt zurück.','Sobald der tatsächliche Bison-Cooldown abgelaufen ist, nutze Bison erneut und schicke einen weiteren Sammelmarsch für eine zweite Sofort-Sammlung.'],['Wichtig: Bison wurde bereits vor dem Reset aktiviert, während die vorbereiteten Truppen aktiv gesammelt haben. Dadurch läuft der Cooldown schon vor Beginn des Sammeltags.','Bereite heute außerdem die Intel-Missionen für morgen nach dem separaten Plan vor.']],
      ['Trucks und Geheimdienstmissionen',['Schließe nach dem Reset die offenen 16:00-UTC-Missionen sowie Pans zusätzliche Mission ab und hole die Belohnungen ab.','Erledige und beanspruche auch die neuen Intel-Missionen des Tages.','Nutze deine Trucks.'],['Beim Allianzgemenge zählen Intel-Missionen beim Abschließen. Das Zurückhalten bereits abgeschlossener 08:00-UTC-Missionen wäre nur bei einem zusätzlichen Start von Golden Glaives nötig.','Truppen, Ausbauressourcen und Sammelabschlüsse für ihre passenden Tage aufsparen.']],
      ['Trucks und Sammeln',['Nutze deine Trucks.','Lass die vor dem Reset gestarteten Sammler erst nach dem Reset zurückkehren – erst dann zählen die gesammelten Ressourcen.','Schicke danach einen neuen Sammelmarsch los. Die vor dem Reset aktivierte Bison-Fähigkeit wird sofort ausgelöst und der Marsch kehrt direkt vollständig gesammelt zurück.','Sobald der tatsächliche Bison-Cooldown abgelaufen ist, nutze Bison erneut und schicke einen weiteren Sammelmarsch für eine zweite Sofort-Sammlung.'],['Wichtig: Bison wurde bereits vor dem Reset aktiviert, während die vorbereiteten Truppen aktiv gesammelt haben. Dadurch läuft der Cooldown schon vor Beginn des Sammeltags.','Andere KvK-intensive Aufgaben heute auslassen.']],
      ['Trucks, Truppenausbildung und Geheimdienstmissionen',['Nutze deine Trucks und Geheimdienstmissionen.','Lass vorbereitete lange Trainingspakete heute fertig werden.'],['Nur bis zur lohnenden Belohnungsstufe spielen und weitere Speedups für KvK sparen.']],
      ['Trucks sowie Bestien und Terrors',['Nutze deine Trucks.','Jage Bestien und Terrors für die heutige Phase.'],['Keine KvK-Ausbauressourcen nur für zusätzliche Brawl-Punkte einsetzen.']],
      ['Trucks sowie Bestien und Terrors',['Nutze deine Trucks.','Jage Bestien und Terrors für die heutige Phase.'],['Keine KvK-Ausbauressourcen nur für zusätzliche Brawl-Punkte einsetzen.']]
    ],
    en:[
      ['Trucks and gathering',['Use your trucks.','Let the gatherers sent before reset return only after reset – only then do the gathered resources score.','Then send one new gathering march. The Bison ability activated before reset triggers immediately, and the march returns at once with a full load.','Once Bison’s actual cooldown has ended, use Bison again and send another gathering march for a second instant collection.'],['Important: Bison was already activated before reset while the prepared troops were actively gathering. This starts the cooldown before the gathering day begins.','Also prepare tomorrow’s Intel Missions today using the separate plan.']],
      ['Trucks and Intel Missions',['After reset, complete the unfinished 16:00 UTC missions and Pan’s extra mission, then claim their rewards.','Complete and claim the new Intel Missions for the day as well.','Use your trucks.'],['Alliance Brawl scores Intel Missions when they are completed. Holding rewards from completed 08:00 UTC missions would only be needed if Golden Glaives also started.','Save troops, upgrades and gathering completions for their scoring days.']],
      ['Trucks and gathering',['Use your trucks.','Let the gatherers sent before reset return only after reset – only then do the gathered resources score.','Then send one new gathering march. The Bison ability activated before reset triggers immediately, and the march returns at once with a full load.','Once Bison’s actual cooldown has ended, use Bison again and send another gathering march for a second instant collection.'],['Important: Bison was already activated before reset while the prepared troops were actively gathering. This starts the cooldown before the gathering day begins.','Skip other KvK-intensive tasks today.']],
      ['Trucks, troop training and Intel Missions',['Use your trucks and Intel Missions.','Finish prepared long troop-training batches today.'],['Stop at a worthwhile reward tier and save further speedups for KvK.']],
      ['Trucks plus beasts and terrors',['Use your trucks.','Hunt beasts and terrors for today’s stage.'],['Do not spend KvK upgrade resources only for extra Brawl points.']],
      ['Trucks plus beasts and terrors',['Use your trucks.','Hunt beasts and terrors for today’s stage.'],['Do not spend KvK upgrade resources only for extra Brawl points.']]
    ],
    fr:[
      ['Camions et collecte',['Utilise tes camions.','Laisse les collecteurs envoyés avant le reset revenir uniquement après le reset – les ressources ne rapportent des points qu’à ce moment-là.','Envoie ensuite une nouvelle marche de collecte. La compétence du Bison activée avant le reset se déclenche immédiatement et la marche revient aussitôt avec une collecte complète.','Lorsque le véritable temps de recharge du Bison est terminé, utilise-le de nouveau et envoie une autre marche pour une deuxième collecte instantanée.'],['Important : le Bison a déjà été activé avant le reset pendant que les troupes préparées collectaient. Son temps de recharge a donc commencé avant le jour de collecte.','Prépare également aujourd’hui les missions de renseignement de demain selon le plan séparé.']],
      ['Camions et missions de renseignement',['Après le reset, termine les missions de 16:00 UTC laissées en attente ainsi que la mission supplémentaire de Pan, puis récupère leurs récompenses.','Termine et récupère également les nouvelles missions de renseignement du jour.','Utilise tes camions.'],['Dans Alliance Brawl, les missions de renseignement rapportent des points lorsqu’elles sont terminées. Conserver les récompenses des missions de 08:00 UTC ne serait nécessaire que si Golden Glaives commençait également.','Garde troupes, améliorations et collectes pour les jours correspondants.']],
      ['Camions et collecte',['Utilise tes camions.','Laisse les collecteurs envoyés avant le reset revenir uniquement après le reset – les ressources ne rapportent des points qu’à ce moment-là.','Envoie ensuite une nouvelle marche de collecte. La compétence du Bison activée avant le reset se déclenche immédiatement et la marche revient aussitôt avec une collecte complète.','Lorsque le véritable temps de recharge du Bison est terminé, utilise-le de nouveau et envoie une autre marche pour une deuxième collecte instantanée.'],['Important : le Bison a déjà été activé avant le reset pendant que les troupes préparées collectaient. Son temps de recharge a donc commencé avant le jour de collecte.','Évite aujourd’hui les autres tâches coûteuses en ressources KvK.']],
      ['Camions, entraînement et missions de renseignement',['Utilise tes camions et missions de renseignement.','Termine aujourd’hui les longs entraînements préparés.'],['Arrête-toi à un palier rentable et garde les accélérateurs restants pour le KvK.']],
      ['Camions, bêtes et terreurs',['Utilise tes camions.','Chasse les bêtes et les terreurs pour la phase du jour.'],['Ne dépense pas de ressources d’amélioration KvK uniquement pour des points supplémentaires.']],
      ['Camions, bêtes et terreurs',['Utilise tes camions.','Chasse les bêtes et les terreurs pour la phase du jour.'],['Ne dépense pas de ressources d’amélioration KvK uniquement pour des points supplémentaires.']]
    ]
  };
  const gatheringPrep={
    de:{title:'Sammeltag morgen und Truppentag Donnerstag vorbereiten',steps:['Schicke vor dem Reset lange Sammler los, sodass sie erst nach dem Reset zurückkehren.','Aktiviere Bison, sobald diese Truppen aktiv sammeln. So beginnt der tatsächliche Cooldown bereits vor dem Reset.','Rufe die vorbereiteten Sammler nicht vor dem Reset zurück.','Bewirb dich frühzeitig für den Ministerposten Noble Advisor und wähle selbst ein passendes Zeitfenster.','Kombiniere den Ministerbonus mit dem Trainingsboost für 3.000 Edelsteine. Starte die langen Trainingspakete rechtzeitig, damit sie erst am Donnerstag nach dem Reset enden; mit beiden Boni beträgt die Trainingszeit ungefähr zwei Tage.']},
    en:{title:'Prepare tomorrow’s gathering and Thursday’s troop day',steps:['Send long gathering marches before reset so they return only after reset.','Activate Bison once those troops are actively gathering. This starts the actual cooldown before reset.','Do not recall the prepared gatherers before reset.','Apply early for the Noble Advisor ministerial post and select a suitable time slot yourself.','Combine the ministerial bonus with the 3,000-gem training boost. Start long training batches in time to finish only after reset on Thursday; with both bonuses, training takes about two days.']},
    fr:{title:'Préparer la collecte de demain et les troupes de jeudi',steps:['Envoie de longues marches de collecte avant le reset afin qu’elles reviennent seulement après celui-ci.','Active le Bison dès que ces troupes collectent activement. Le véritable temps de recharge commence ainsi avant le reset.','Ne rappelle pas les collecteurs préparés avant le reset.','Postule tôt au poste ministériel Noble Advisor et choisis toi-même un créneau adapté.','Combine le bonus ministériel avec le bonus d’entraînement à 3 000 gemmes. Lance les longs entraînements assez tôt pour qu’ils se terminent seulement après le reset de jeudi ; avec les deux bonus, ils durent environ deux jours.']}
  };
  const trainingPrep={
    de:{title:'Truppentag morgen – letzte Vorbereitung',steps:['Falls noch nicht geschehen: Sichere dir sofort ein passendes Noble-Advisor-Zeitfenster.','Aktiviere vor dem Start der Trainingspakete den Ministerbonus und den Trainingsboost für 3.000 Edelsteine.','Plane das Ende der Trainingspakete für Donnerstag nach dem Reset – nicht vorher.']},
    en:{title:'Troop day tomorrow – final preparation',steps:['If you have not already done so, secure a suitable Noble Advisor time slot immediately.','Activate the ministerial bonus and the 3,000-gem training boost before starting the batches.','Time the training batches to finish after reset on Thursday, not before.']},
    fr:{title:'Journée des troupes demain – dernière préparation',steps:["Si ce n’est pas déjà fait, réserve immédiatement un créneau adapté pour Noble Advisor.",'Active le bonus ministériel et le bonus d’entraînement à 3 000 gemmes avant de lancer les séries.','Planifie la fin des entraînements après le reset de jeudi, pas avant.']}
  };
  function brawlPlan(e,date,lang){const phase=Math.floor((new Date(`${date}T00:00:00Z`)-new Date(`${e.start}T00:00:00Z`))/day)+1;if(phase<1||phase>6)return null;const [points,steps,details]=brawlCopy[lang][phase-1],prepare=phase===2?gatheringPrep[lang]:(phase===3?trainingPrep[lang]:null),kvkNote={de:'Bitte verbrauche für das Allianzgemenge keine KvK-Ressourcen, die in der heutigen Phase Punkte bringen.',en:"Please do not spend KvK resources that score during today’s Alliance Brawl stage.",fr:"Merci de ne pas dépenser les ressources KvK qui rapportent des points pendant la phase d’Alliance Brawl du jour."}[lang];return{points,steps,details:[...details,kvkNote],prepare,phase}}

  const guides={
    fishing:{
      de:{steps:['Verbessere zuerst die Leine, danach den Haken und zuletzt das Gewicht.','Priorisiere leuchtende Fische und Gegenstände für zusätzliche Münzen.','Nutze Pause → Rückzug, wenn du mit einem Fang nicht zufrieden bist; das Ticket bleibt erhalten.'],details:['Jede Tiefe besitzt eigene Fische. Schwimmt ein Fisch nach rechts, weiche links aus.','Der Schwanz ist ungefährlich; gefangen wird über Fischmaul, Taucherkopf oder Gegenstandsmitte.','In der Dunkelheit den Haken an eine Seite bewegen und bei einem Treffer neu starten.','Spezialgegenstände bleiben nach dem Turnier erhalten – als F2P für spätere Turniere sparen.']},
      en:{steps:['Upgrade the line first, then the hook, and the weight last.','Prioritize glowing fish and objects for extra coins.','Use Pause → Retreat if you dislike a catch; the ticket is preserved.'],details:['Each depth has its own fish. If a fish swims right, dodge it on the left.','The tail is safe; the catch trigger is the fish’s mouth, diver’s head or center of an object.','In darkness, move the hook to one side and restart after hooking a fish.','Special items carry over – F2P players can save them for later tournaments.']},
      fr:{steps:["Améliore d’abord la ligne, puis l’hameçon et enfin le poids.","Priorise les poissons et objets lumineux pour obtenir des pièces supplémentaires.","Utilise Pause → Retraite si la prise ne te convient pas ; le ticket est conservé."],details:["Chaque profondeur possède ses propres poissons. S’ils nagent vers la droite, évite-les par la gauche.","La queue est sans danger ; la capture se déclenche à la bouche, à la tête du plongeur ou au centre de l’objet.","Dans l’obscurité, déplace l’hameçon d’un côté et recommence après avoir accroché un poisson.","Les objets spéciaux sont conservés : les joueurs F2P peuvent les garder pour les prochains tournois."]}
    },
    viking:{
      de:{steps:['Schicke alle Truppen als Verstärkung zu anderen Mitgliedern; in deiner Stadt bleiben nur die drei stärksten Helden und keine Truppen.','Lösche das Feuer in deiner Stadt.','Schicke bei Welle 10 und 20 deine Truppen zum Ebenen-HQ.','Heile während des Events nicht.'],details:['Eine Welle ist gewonnen, sobald mindestens 50 % der angreifenden Truppen getötet wurden.','Nach zwei verlorenen Verteidigungen endet der Angriff auf deine Stadt; durch Verstärkungen kannst du weiter punkten.','Wenn du offline bist, schicke vorher alle Truppen zu Verbündeten und vereinbare möglichst eine gegenseitige Verstärkung.']},
      en:{steps:['Send all troops to reinforce other members; keep only your three strongest heroes and no troops in your city.','Extinguish the fire in your city.','Send troops to the Plains HQ for waves 10 and 20.','Do not heal during the event.'],details:['A wave is defended once at least 50% of the attacking troops are killed.','After two failed defences, attacks on your city stop; you can still score by reinforcing allies.','If offline, send all troops to allies beforehand and arrange reciprocal reinforcements if possible.']},
      fr:{steps:["Envoie toutes tes troupes renforcer d’autres membres ; garde seulement tes trois meilleurs héros et aucune troupe en ville.","Éteins l’incendie dans ta ville.","Envoie tes troupes au QG des Plaines aux vagues 10 et 20.","Ne soigne pas pendant l’événement."],details:["Une vague est défendue dès qu’au moins 50 % des troupes ennemies sont éliminées.","Après deux défaites, les attaques contre ta ville cessent ; tu peux continuer à marquer par les renforts.","Si tu es absent, envoie toutes tes troupes chez des alliés et organise si possible un échange de renforts."]}
    },
    eternity:{
      de:{points:'Orichalcum durch Wachen, Adern und Aderausbrüche',steps:['Zoome heraus und suche einen wenig belegten Bereich. Besiege bevorzugt Cäsars Wachen der Stufe 2.','Baue den Fähigkeitenbaum rechts → rechts → links → links → rechts aus.','Ab Fähigkeit 3: Besetze mit einem Marsch jede Minute eine Ader für 5.000 Orichalcum; die übrigen Märsche besiegen Wachen.','Aktiviere Fähigkeit 5 nur beim Aderausbruch und schicke dann alle Märsche zu den Adern.'],details:['Fähigkeit 1: 1.500 Orichalcum je besiegter Cäsar-Wache.','Fähigkeit 2: +25 % Marschgeschwindigkeit.','Fähigkeit 4: +15 % Sammelgeschwindigkeit.','Fähigkeit 5: +66 % Sammelgeschwindigkeit für 60 Sekunden, 5 Minuten Abklingzeit. Währenddessen die Truppen nicht vor Ablauf der fünf Minuten zurückrufen.']},
      en:{points:'Orichalcum from guards, veins and vein outbursts',steps:['Zoom out and find a quiet area. Prioritize level 2 Caesar Guards.','Build the skill tree right → right → left → left → right.','From skill 3: use one march to occupy a vein every minute for 5,000 Orichalcum; keep the other marches on guards.','Activate skill 5 only during a vein outburst, then send all marches to the veins.'],details:['Skill 1: 1,500 Orichalcum per defeated Caesar Guard.','Skill 2: +25% march speed.','Skill 4: +15% gathering speed.','Skill 5: +66% gathering speed for 60 seconds, 5-minute cooldown. Do not recall troops before the five minutes have passed.']},
      fr:{points:"Orichalque grâce aux gardes, filons et éruptions",steps:["Dézoome et choisis une zone peu fréquentée. Priorise les gardes de César de niveau 2.","Améliore l’arbre : droite → droite → gauche → gauche → droite.","Dès la compétence 3 : occupe un filon chaque minute avec une marche pour 5 000 Orichalques ; les autres combattent les gardes.","Active la compétence 5 uniquement pendant une éruption et envoie alors toutes les marches aux filons."],details:["Compétence 1 : 1 500 Orichalques par garde de César vaincu.","Compétence 2 : +25 % de vitesse de marche.","Compétence 4 : +15 % de vitesse de collecte.","Compétence 5 : +66 % de vitesse de collecte pendant 60 secondes, recharge de 5 minutes. Ne rappelle pas les troupes avant la fin des cinq minutes."]}
    },
    cesare:{
      de:{steps:['Greife jeden Captain zunächst mit genau einem Soldaten und ohne Helden an.','Warte, bis alle aktiven Mitglieder einmal getroffen und ihre Teilnahmebelohnung gesichert haben.','Erst danach darf der Captain mit vollständigen Märschen besiegt werden.'],details:['So erhält die gesamte Allianz die maximale Zahl an Teilnahmebelohnungen.']},
      en:{steps:['Attack each Captain first with exactly one troop and no hero.','Wait until all active members have landed one hit and secured participation rewards.','Only then finish the Captain with full marches.'],details:['This maximizes participation rewards for the whole alliance.']},
      fr:{steps:["Attaque d’abord chaque capitaine avec exactement un soldat et sans héros.","Attends que tous les membres actifs aient porté un coup et obtenu la récompense de participation.","Ensuite seulement, termine le capitaine avec des marches complètes."],details:["Cette méthode maximise les récompenses de participation de toute l’alliance."]}
    },
    golden:{
      de:{steps:['00:00 UTC: Missionen abschließen und Belohnungen abholen.','08:00 UTC: Missionen abschließen, Belohnungen nicht abholen.','16:00 UTC: Missionen weder abschließen noch abholen. Danach Pans zusätzliche Geheimdienstmission aktivieren.','Nach dem nächsten Reset die vorbereiteten Missionen abschließen und gesammelt abholen.'],details:['Diese Vorbereitung erzeugt zusätzliche Punkte für die nächste Prephase.']},
      en:{steps:['00:00 UTC: complete missions and claim rewards.','08:00 UTC: complete missions but do not claim rewards.','16:00 UTC: neither complete nor claim missions. Then activate Pan’s extra Intel Mission.','After the next reset, complete and claim the prepared missions.'],details:['This preparation creates extra points for the next pre-phase.']},
      fr:{steps:["00:00 UTC : termine les missions et récupère les récompenses.","08:00 UTC : termine les missions sans récupérer les récompenses.","16:00 UTC : ne termine ni ne récupère les missions. Active ensuite la mission de renseignement supplémentaire de Pan.","Après le reset suivant, termine et récupère les missions préparées."],details:["Cette préparation rapporte des points supplémentaires pour la prochaine préphase."]}
    },
    kill:{
      de:{steps:['Ein Schild ist aufgrund der Servergesetze für NRW-Mitglieder nicht notwendig.','Schicke während des Kill Events keine Sammler auf Ressourcenfelder.','Halte deine Krankenstation frei und beachte die Castle-Battle-Ansagen auf Discord.'],details:['Stadtangriffe sind grundsätzlich verboten. Ausnahmen: allianzlose Städte, Ein-Mitglied-Allianzen und KOK.','Kill-Event-Punkte können während der Castle Battle gesammelt werden. Danach kann wieder sicher gesammelt werden.']},
      en:{steps:['NRW members do not need a shield because of the server laws.','Do not send gatherers to resource tiles during the Kill Event.','Keep your infirmary clear and follow Castle Battle calls on Discord.'],details:['City attacks are prohibited except against cities without an alliance, one-member alliances and KOK.','Kill Event points can be earned during Castle Battle. Gathering is safe again afterwards.']},
      fr:{steps:["Les membres NRW n’ont pas besoin de bouclier grâce aux lois du serveur.","N’envoie aucun collecteur sur les ressources pendant le Kill Event.","Garde ton infirmerie libre et suis les consignes de Castle Battle sur Discord."],details:["Les attaques de villes sont interdites, sauf contre les joueurs sans alliance, les alliances d’un membre et KOK.","Les points du Kill Event peuvent être gagnés pendant la Castle Battle. La collecte redevient sûre ensuite."]}
    }
  };
  function planFromFeed(e,date,lang){const plan=e.dailyPlans?.[date];if(!plan)return null;return{points:localized(plan.points,lang),steps:plan.steps?.[lang]||plan.steps?.en||[],prepare:plan.prepare?{title:localized(plan.prepare.title,lang),steps:plan.prepare.steps?.[lang]||plan.prepare.steps?.en||[]}:null,details:plan.note?[localized(plan.note,lang)]:[],limits:plan.limits||null}}
  function coachFor(e,date,lang){const kind=eventKind(e),manual=kind==='brawl'?brawlPlan(e,date,lang):(guides[kind]?.[lang]||null),feed=planFromFeed(e,date,lang),rhythm=e.rhythmCoach?.[lang]||e.rhythmCoach?.en,tips=e.tips?.[lang]||e.tips?.en||[],knowledge=knowledgeCoachFor(e,lang),selected=manual||feed||rhythm||{steps:tips.slice(0,3),details:tips.slice(3)},chosen={...selected,steps:[...(selected.steps||[])],details:[...(selected.details||[])]};if(feed&&manual){chosen.prepare=feed.prepare||chosen.prepare;if(feed.points&&!chosen.points)chosen.points=feed.points}if(knowledge){if(!chosen.steps.length)chosen.steps=[...knowledge.steps];const additions=[...(knowledge.details||[])];for(const detail of additions){if(detail&&!chosen.details.includes(detail))chosen.details.push(detail)}}return chosen}
  const whyText={
    de:{
      bison:'Der Cooldown läuft bereits, während deine vorbereiteten Truppen sammeln. So verlierst du am Punktetag keine Wartezeit: Nach ihrer Rückkehr kannst du Bison früher für eine Sofort-Sammlung und nach dem nächsten Cooldown erneut nutzen.',
      intel:'Beim Allianzgemenge entstehen die Punkte durch das Abschließen der Intel-Mission. Vorbereitete 16:00-UTC- und Pan-Missionen können deshalb gezielt nach dem Reset abgeschlossen werden.',
      armament:'Amulettmaterialien werden auch für KvK benötigt. Die Belohnungen dieses Wettbewerbs rechtfertigen den Verbrauch nicht; Auslassen schützt deine KvK-Reserven.',
      merchant:'Später gestartete Karawanen werden erfahrungsgemäß seltener angegriffen. Deshalb empfiehlt NRW, ungefähr zehn Stunden nach dem Reset zu warten.'
    },
    en:{
      bison:'The cooldown already runs while your prepared troops are gathering. This avoids losing time on the scoring day: after they return, you can use Bison earlier for an instant collection and again after the next cooldown.',
      intel:'Alliance Brawl awards points when Intel Missions are completed. Prepared 16:00 UTC and Pan missions can therefore be completed deliberately after reset.',
      armament:'Charm materials are also needed for KvK. This competition’s rewards do not justify spending them; skipping it protects your KvK reserves.',
      merchant:'Caravans sent later are usually attacked less often. NRW therefore recommends waiting about ten hours after reset.'
    },
    fr:{
      bison:'Le temps de recharge commence déjà pendant que tes troupes préparées collectent. Tu ne perds donc pas de temps le jour des points : après leur retour, tu peux utiliser le Bison plus tôt pour une collecte instantanée, puis de nouveau après la recharge suivante.',
      intel:'L’Alliance Brawl accorde les points lorsque les missions de renseignement sont terminées. Les missions de 16:00 UTC et de Pan peuvent donc être terminées volontairement après le reset.',
      armament:'Les matériaux de charme sont également nécessaires pour le KvK. Les récompenses de cette compétition ne justifient pas leur dépense ; l’ignorer protège tes réserves KvK.',
      merchant:'Les caravanes envoyées plus tard sont généralement moins attaquées. NRW recommande donc d’attendre environ dix heures après le reset.'
    }
  };
  function whyFor(e,coach,lang){const kind=eventKind(e),all=[...(coach.steps||[]),...(coach.details||[]),...(coach.prepare?.steps||[])].join(' ').toLowerCase();if(kind==='brawl'&&all.includes('bison'))return whyText[lang].bison;if(kind==='brawl'&&(all.includes('intel')||all.includes('geheimdienst')||all.includes('renseignement')))return whyText[lang].intel;if(kind==='armament')return whyText[lang].armament;if(kind==='merchant')return whyText[lang].merchant;return''}
  function priorityCards(date,lang,now){const rank={kill:120,brawl:110,armament:100,officer:90,viking:85,eternity:80,merchant:70,fishing:55,cesare:50,golden:45,transfer:20,generic:30};return eventsFor(date).map(e=>{const coach=coachFor(e,date,lang)||{steps:[],details:[]},kind=eventKind(e);let action=coach.prepare?.steps?.length?`${coach.prepare.title}: ${coach.prepare.steps[0]}`:(coach.steps?.[0]||coach.details?.[0]||'');if(kind==='merchant'&&now.getUTCHours()>=10&&coach.steps?.[1])action=coach.steps[1];return{e,action,score:(rank[kind]||30)+(coach.prepare?.steps?.length?25:0)+(coach.limits?20:0)}}).filter(x=>x.action).sort((a,b)=>b.score-a.score).slice(0,3)}
  function renderPriorities(date,lang,now){const rail=document.getElementById('priorityRail'),items=priorityCards(date,lang,now);rail.hidden=!items.length;document.getElementById('priorityItems').innerHTML=items.map(({e,action},index)=>`<button class="priority-item" type="button" data-priority-key="today:${safe(date)}:${safe(e.id)}"><span class="priority-number">0${index+1}</span><span class="priority-icon">${eventIcon(e)}</span><span><strong>${safe(localized(e.name,lang))}</strong><small>${safe(action)}</small></span><i aria-hidden="true">→</i></button>`).join('')}
  function bindPriorityCards(){document.querySelectorAll('[data-priority-key]').forEach(button=>button.addEventListener('click',()=>{const card=document.querySelector(`[data-event-key="${CSS.escape(button.dataset.priorityKey)}"]`);if(!card)return;card.open=true;card.scrollIntoView({behavior:'smooth',block:'start'})}))}

  function confidenceLabel(e,lang){const t=ui[lang];if(e.confidence==='predicted')return t.predicted;if(e.confidence==='confirmed-ingame'||e.confidence==='official'||e.confidence==='public-timeline')return t.rhythm;if(e.manual)return t.manual;return''}
  function eventSummary(e,lang,status,label,t){return`<summary class="event-card-summary"><div class="event-card-icon">${eventIcon(e)}</div><div><span class="event-status">${safe(status)}</span><h3>${safe(localized(e.name,lang))}</h3></div><div class="event-card-meta">${label?`<span class="verified-badge">${safe(label)}</span>`:''}<span class="expand-copy"><span class="when-closed">${safe(t.open)}</span><span class="when-open">${safe(t.close)}</span></span><span class="event-chevron" aria-hidden="true"></span></div></summary>`}
  function eventCard(e,date,lang,status,group,index){const t=ui[lang],coach=coachFor(e,date,lang)||{steps:[],details:[]},steps=coach.steps||[],details=coach.details||[],label=confidenceLabel(e,lang),key=`${group}:${date}:${e.id}`,isOpen=expandedCards.has(key),why=whyFor(e,coach,lang);const stepHtml=steps.map((step,stepIndex)=>`<li><b>${stepIndex+1}</b><span>${safe(step)}</span></li>`).join('');const detailHtml=details.length?`<section class="event-notes"><h4>${safe(t.details)}</h4><ul>${details.map(x=>`<li>${safe(x)}</li>`).join('')}</ul></section>`:'';const prepHtml=coach.prepare?.steps?.length?`<div class="prepare-box"><strong>${safe(coach.prepare.title)}</strong><p>${safe(coach.prepare.steps.join(' • '))}</p></div>`:'';const scoreHtml=coach.points?`<div class="score-focus"><span>🎯 ${lang==='de'?'PUNKTEQUELLEN':lang==='fr'?"SOURCES DE POINTS":'SCORING'}</span><strong>${safe(coach.points)}</strong></div>`:'';const tipHtml=e.manual?`<span class="nrw-tip-label">${safe(t.manual)}</span>`:'';const whyHtml=why?`<aside class="why-box"><strong><span aria-hidden="true">?</span>${safe(t.why)}</strong><p>${safe(why)}</p></aside>`:'';const limits=coach.limits,limitNote=localized(limits?.note,lang)||t.limitNote;const limitsHtml=limits?(limits.target?`<div class="law-limit"><div><span>${t.target}</span><strong>${num(limits.target)}</strong></div><i></i><div><span>${t.hardCap}</span><strong>${num(limits.hardCap)}</strong></div><p>${safe(limitNote)}</p></div>`:`<div class="law-limit law-limit-single"><div><span>${t.hardCap}</span><strong>${num(limits.hardCap)}</strong></div><p>${safe(limitNote)}</p></div>`):'';const sourceUrl=e.sourceUrl||guideSourceFor(e),source=sourceUrl?`<a class="guide-link" href="${safe(sourceUrl)}" target="_blank" rel="noopener">${t.source} ↗</a>`:'';return`<details class="event-card" name="${safe(group)}" data-event-key="${safe(key)}"${isOpen?' open':''}>${eventSummary(e,lang,status,label,t)}<div class="event-card-body">${tipHtml}${scoreHtml}${prepHtml}<div class="action-block"><h4>${t.now}</h4><ol>${stepHtml}</ol></div>${whyHtml}${limitsHtml}${detailHtml}${source}</div></details>`}

  function mythicVirtual(date,lang){const weekday=new Date(`${date}T00:00:00Z`).getUTCDay();const data={de:{name:'Mythische Prüfung',status:'WÖCHENTLICH',ratio:'Infanterie/Kavallerie/Bogenschützen',zones:{col:['Kolosseum','50/10/40'],forest:['Wald des Lebens','50/15/35'],crystal:['Kristallhöhle','60/20/20'],knowledge:['Wissensnetzwerk','50/20/30'],molten:['Schmelzfestung','60/15/25'],radiant:['Strahlender Gipfel','Team 1: 50/20/30. Kavalleriehelden der Teams tauschen; Team 2: 50/35/15.']}},en:{name:'Mythic Trial',status:'WEEKLY',ratio:'Infantry/Cavalry/Archers',zones:{col:['Colosseum','50/10/40'],forest:['Forest of Life','50/15/35'],crystal:['Crystal Cave','60/20/20'],knowledge:['Knowledge Network','50/20/30'],molten:['Molten Fort','60/15/25'],radiant:['Radiant Peak','Team 1: 50/20/30. Swap the cavalry heroes between teams; Team 2: 50/35/15.']}},fr:{name:'Épreuve mythique',status:'HEBDOMADAIRE',ratio:'Infanterie/Cavalerie/Archers',zones:{col:['Colisée','50/10/40'],forest:['Forêt de la vie','50/15/35'],crystal:['Grotte de cristal','60/20/20'],knowledge:['Réseau du savoir','50/20/30'],molten:['Forteresse en fusion','60/15/25'],radiant:['Pic radieux','Équipe 1 : 50/20/30. Échange les héros de cavalerie ; équipe 2 : 50/35/15.']}}}[lang];const keys=weekday===0?['radiant']:(weekday<=2?['col']:(weekday<=4?['forest','crystal']:['knowledge','molten']));return{id:`mythic-${date}`,icon:'🔮',iconUrl:'https://kingshotdata.com/uploads/2025/10/mystrical-trial.webp',manual:true,name:{[lang]:data.name},virtualCoach:{steps:keys.map(k=>`${data.zones[k][0]}: ${data.zones[k][1]} · ${data.ratio}`),details:[lang==='de'?'Formation vor dem Start kontrollieren; die Werte sind NRW-Ausgangsformationen.':lang==='fr'?"Contrôle la formation avant le départ ; ces valeurs sont les formations de départ NRW.":'Check the formation before starting; these are NRW starting formations.']},virtualStatus:data.status}}
  function championshipVirtual(date,lang){const weekday=new Date(`${date}T00:00:00Z`).getUTCDay();if(weekday!==1&&weekday!==2)return null;const data={de:{name:'Allianzmeisterschaft · Anmeldung',steps:['Aktiviere deine Pet-Buffs vor der Anmeldung.','Ab 250 Mio. Spielerkraft: 60/40/0 mit defensiven Helden; tausche bei Bedarf die beste Ausrüstung.','Unter 250 Mio. Spielerkraft: 50/20/30 mit deinen drei besten Helden.','Melde dich ausschließlich in der mittleren Reihe an.'],status:'ANMELDUNG OFFEN'},en:{name:'Alliance Championship · Registration',steps:['Activate your Pet Buffs before registering.','At 250M power or above: 60/40/0 with defensive heroes; move your best gear if needed.','Below 250M power: 50/20/30 with your three best heroes.','Register only in the middle lane.'],status:'REGISTRATION OPEN'},fr:{name:'Championnat d’alliance · Inscription',steps:["Active tes bonus de familier avant l’inscription.","À partir de 250 M de puissance : 60/40/0 avec des héros défensifs ; transfère le meilleur équipement si nécessaire.","Sous 250 M de puissance : 50/20/30 avec tes trois meilleurs héros.","Inscris-toi uniquement dans la ligne centrale."],status:'INSCRIPTION OUVERTE'}}[lang];return{id:`championship-${date}`,icon:'🏆',iconUrl:'https://kingshotguides.com/wp-content/uploads/2025/06/alliance-championship-icon.webp',iconFit:'cover',manual:true,name:{[lang]:data.name},virtualCoach:{steps:data.steps,details:[]},virtualStatus:data.status}}
  function virtualCard(e,date,lang,group,index){const t=ui[lang],key=`${group}:${date}:${e.id}`,isOpen=expandedCards.has(key),steps=e.virtualCoach.steps.map((step,stepIndex)=>`<li><b>${stepIndex+1}</b><span>${safe(step)}</span></li>`).join(''),details=e.virtualCoach.details.length?`<section class="event-notes"><h4>${safe(t.details)}</h4><ul>${e.virtualCoach.details.map(x=>`<li>${safe(x)}</li>`).join('')}</ul></section>`:'';return`<details class="event-card" name="${safe(group)}" data-event-key="${safe(key)}"${isOpen?' open':''}>${eventSummary(e,lang,e.virtualStatus,t.manual,t)}<div class="event-card-body"><div class="action-block"><h4>${t.now}</h4><ol>${steps}</ol></div>${details}</div></details>`}
  function cardsFor(date,lang,status,group){const entries=eventsFor(date).map(e=>({e,virtual:false})).concat([championshipVirtual(date,lang),mythicVirtual(date,lang)].filter(Boolean).map(e=>({e,virtual:true})));return entries.map(({e,virtual},index)=>virtual?virtualCard(e,date,lang,group,index):eventCard(e,date,lang,status,group,index))}
  function bindEventCards(){document.querySelectorAll('.event-card[data-event-key]').forEach(card=>card.addEventListener('toggle',()=>{const key=card.dataset.eventKey;if(card.open){document.querySelectorAll(`.event-card[name="${card.getAttribute('name')}"]`).forEach(other=>{if(other!==card)other.open=false});expandedCards.add(key)}else expandedCards.delete(key)}))}
  function kvkPrepWindow(now){let start=kvkPrepBase;while(now.getTime()>=start+kvkPrepDuration)start+=kvkCycle;return{start:new Date(start),active:now.getTime()>=start}}
  function nextBearAt(hour,minute){const now=new Date();for(let add=0;add<4;add++){const x=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+add,hour,minute));if(isBearDay(x)&&x>now)return x}return new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+2,hour,minute))}
  function fmtCountdown(target){let s=Math.max(0,Math.floor((target-Date.now())/1000)),days=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return(days?days+'d ':'')+[h,m,sec].map(v=>String(v).padStart(2,'0')).join(':')}
  function placeReleaseCard(today){const card=document.getElementById('gen6Card'),priority=document.getElementById('priorityGrid'),lower=document.getElementById('releaseLower'),section=document.getElementById('releaseDetails'),released=today>releaseDay;if(released&&card.parentElement!==lower)lower.appendChild(card);if(!released&&card.parentElement!==priority)priority.appendChild(card);section.hidden=!released;priority.classList.toggle('single',released)}
  function renderDynamic(){const lang=body.dataset.lang||'en',t=ui[lang],now=new Date(),todayUTC=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())),tomorrow=new Date(todayUTC.getTime()+day),today=dateKey(todayUTC),next=dateKey(tomorrow),locale=t.locale;document.getElementById('weekday').textContent=now.toLocaleDateString(locale,{weekday:'long',timeZone:'UTC'});document.getElementById('dateLabel').textContent=now.toLocaleDateString(locale,{day:'2-digit',month:'short',timeZone:'UTC'}).toUpperCase();const kvk=kvkPrepWindow(now);document.getElementById('kvkStartLabel').textContent=kvk.start.toLocaleDateString(locale,{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).toUpperCase()+' · 00:00 UTC';const serverAge=Math.floor((todayUTC.getTime()-serverOpened)/day);document.querySelectorAll('[data-server-age]').forEach(el=>el.textContent=serverAge);placeReleaseCard(today);renderPriorities(today,lang,now);const todayCards=cardsFor(today,lang,t.today,'today');document.getElementById('todayEvents').innerHTML=todayCards.length?todayCards.join(''):`<div class="empty-plan">${t.noEvents}</div>`;document.getElementById('tomorrowTitle').textContent=tomorrow.toLocaleDateString(locale,{weekday:'long',day:'2-digit',month:'2-digit',timeZone:'UTC'});document.getElementById('tomorrowTasks').innerHTML=cardsFor(next,lang,t.tomorrow,'tomorrow').join('');bindEventCards();bindPriorityCards();const todayTrapEnd=new Date(todayUTC.getTime()+18.5*3600000),nextDay=nextBearAt(17,0),dateFmt=d=>d.toLocaleDateString(locale,{weekday:'long',day:'2-digit',month:'2-digit',timeZone:'UTC'}),followingBear=isBearDay(todayUTC)&&now<todayTrapEnd?new Date(todayUTC.getTime()+2*day):nextDay;document.getElementById('bearTag').textContent=isBearDay(todayUTC)&&now<todayTrapEnd?t.bearTodayTag:t.bearNextTag;document.getElementById('genTag').textContent=t.genNowTag;document.getElementById('bearDateNote').textContent=(isBearDay(todayUTC)&&now<todayTrapEnd?t.bearToday:t.bearNext).replace('{date}',dateFmt(followingBear))}
  function tick(){const now=new Date(),lang=body.dataset.lang||'en',kvk=kvkPrepWindow(now);document.getElementById('utcClock').textContent=now.toLocaleTimeString('en-GB',{hour12:false,timeZone:'UTC'});document.getElementById('kvkPrepCountdown').textContent=kvk.active?({de:'PREP LÄUFT',en:'PREP ACTIVE',fr:'PREP EN COURS'}[lang]||'PREP ACTIVE'):fmtCountdown(kvk.start);document.getElementById('bt1Countdown').textContent=fmtCountdown(nextBearAt(17,0));document.getElementById('bt2Countdown').textContent=fmtCountdown(nextBearAt(18,30));document.getElementById('gen6Countdown').textContent={de:'Freigeschaltet',en:'Unlocked',fr:'Débloqué'}[lang]||'Unlocked';document.querySelectorAll('[data-count-to]').forEach(el=>{const d=new Date(el.dataset.countTo);el.textContent=d>now?fmtCountdown(d):({de:'Jetzt verfügbar',en:'Available now',fr:'Disponible'}[lang]||'Available now')})}

  const heroDeck=document.getElementById('heroSwipe'),heroCards=[...document.querySelectorAll('.hero-flip')],heroDots=[...document.querySelectorAll('.hero-dots i')];let heroIndex=0,heroScrollTimer;
  const resetHeroFaces=()=>heroCards.forEach(card=>{card.classList.remove('is-flipped');card.setAttribute('aria-pressed','false')});
  const updateHeroControls=index=>{heroIndex=Math.max(0,Math.min(heroCards.length-1,index));heroDots.forEach((dot,dotIndex)=>dot.classList.toggle('active',dotIndex===heroIndex));document.getElementById('heroPrev').disabled=heroIndex===0;document.getElementById('heroNext').disabled=heroIndex===heroCards.length-1};
  const showHero=index=>{resetHeroFaces();heroDeck.classList.add('has-interacted');updateHeroControls(index);heroDeck.scrollTo({left:heroIndex*(heroDeck.clientWidth+12),behavior:'smooth'})};
  heroCards.forEach(card=>card.addEventListener('click',()=>{heroDeck.classList.add('has-interacted');const next=!card.classList.contains('is-flipped');resetHeroFaces();if(next){card.classList.add('is-flipped');card.setAttribute('aria-pressed','true')}}));
  heroDeck.addEventListener('pointerdown',()=>heroDeck.classList.add('has-interacted'),{once:true});heroDeck.addEventListener('scroll',()=>{clearTimeout(heroScrollTimer);heroScrollTimer=setTimeout(()=>{const index=Math.round(heroDeck.scrollLeft/Math.max(1,heroDeck.clientWidth));if(index!==heroIndex)resetHeroFaces();updateHeroControls(index)},80)},{passive:true});document.getElementById('heroPrev').addEventListener('click',()=>showHero(heroIndex-1));document.getElementById('heroNext').addEventListener('click',()=>showHero(heroIndex+1));updateHeroControls(0);
  const profileKey='nrw_member_profile_v1',playerNameInput=document.getElementById('playerName'),playerIdInput=document.getElementById('playerId');try{const p=JSON.parse(localStorage.getItem(profileKey)||'null');if(p){playerNameInput.value=p.playerName||'';playerIdInput.value=p.playerId||'';document.querySelectorAll('#languageGrid input').forEach(i=>i.checked=(p.languages||[]).includes(i.value))}}catch(e){}
  const messages={de:{missing:'Bitte Name, Player ID und Sprache angeben.',invalid:'Die Player ID darf nur Zahlen enthalten.',saved:'Im NRW-Spielerprofil gespeichert ✓',queued:'Zur Prüfung gespeichert ✓',error:'Speichern gerade nicht möglich.'},en:{missing:'Please add name, Player ID and language.',invalid:'Player ID must contain numbers only.',saved:'Saved to your NRW member profile ✓',queued:'Saved for review ✓',error:'Could not save right now.'},fr:{missing:'Ajoute ton nom, Player ID et ta langue.',invalid:'La Player ID doit contenir uniquement des chiffres.',saved:'Enregistré dans ton profil NRW ✓',queued:'Enregistré pour vérification ✓',error:'Enregistrement impossible.'}};
  document.getElementById('saveProfile').addEventListener('click',async()=>{const lang=body.dataset.lang||'en',m=messages[lang],status=document.getElementById('saveStatus'),button=document.getElementById('saveProfile'),profile={schemaVersion:2,playerName:playerNameInput.value.trim(),playerId:playerIdInput.value.trim(),languages:[...document.querySelectorAll('#languageGrid input:checked')].map(i=>i.value),otherLanguage:'',source:'nrw-player-dashboard',updatedAt:new Date().toISOString()};status.className='';if(!profile.playerName||!profile.playerId||!profile.languages.length){status.textContent=m.missing;status.className='error';return}if(!/^\d+$/.test(profile.playerId)){status.textContent=m.invalid;status.className='error';return}button.disabled=true;try{const r=await fetch('https://bdzlgirowutasrsycjfj.supabase.co/functions/v1/nrw-welcome-language',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)}),data=await r.json().catch(()=>({}));if(!r.ok||!data.ok)throw new Error();localStorage.setItem(profileKey,JSON.stringify(profile));status.textContent=data.queued?m.queued:m.saved;status.className='success'}catch(e){status.textContent=m.error;status.className='error'}finally{button.disabled=false}});
  Promise.allSettled([fetch('/dashboard/events.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()),fetch('/dashboard/event-guides.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject())]).then(([feedResult,guideResult])=>{if(feedResult.status==='fulfilled')eventFeed=Array.isArray(feedResult.value.events)?feedResult.value.events:[];if(guideResult.status==='fulfilled')eventGuideDb=guideResult.value||eventGuideDb;renderDynamic()});
  renderDynamic();tick();setInterval(tick,1000);setInterval(renderDynamic,60000);
})();
