/* Browser-only matching of screenshot portrait regions to tiny wiki
 * reference fingerprints generated by GitHub Actions. Images stay on-device.
 * A low-confidence match NEVER becomes an owned hero automatically.
 */
(function(root){
'use strict';
let loading=null;
const SIZE=12;
function data(){
 if(!loading)loading=fetch('./hero-signatures.json',{cache:'force-cache'})
  .then(r=>r.ok?r.json():null).then(j=>{
   if(!j||!Array.isArray(j.portraits)||j.size!==SIZE)return [];
   return j.portraits.map(p=>{
    try{
     const bin=atob(p.rgb);
     if(bin.length!==SIZE*SIZE*3)return null;
     return {name:p.name,rgb:Uint8Array.from(bin,c=>c.charCodeAt(0))};
    }catch(_){return null;}
   }).filter(Boolean);
  }).catch(()=>[]);
 return loading;
}
function candidates(canvas,rect){
 const answer=[],w=rect.w,h=rect.h;
 for(const top of [.02,.11,.20,.28]){
  for(const scale of [.76,.94]){
   const side=w*scale;
   const x=rect.x+(w-side)/2,y=rect.y+h*top;
   if(y+side>rect.y+h*.78)continue;
   const c=document.createElement('canvas');c.width=SIZE;c.height=SIZE;
   const ctx=c.getContext('2d',{willReadFrequently:true});
   ctx.drawImage(canvas,x,y,side,side,0,0,SIZE,SIZE);
   const src=ctx.getImageData(0,0,SIZE,SIZE).data,small=new Uint8Array(SIZE*SIZE*3);
   for(let i=0,j=0;i<src.length;i+=4)for(let k=0;k<3;k++)small[j++]=src[i+k];
   answer.push(small);
  }
 }
 return answer;
}
function difference(a,b){
 let sum=0;
 // Slight illumination variation is expected between wiki crop and HUD.
 // Do NOT discard colour: hair, outfit and hats are distinguishing features.
 for(let i=0;i<a.length;i++)sum+=Math.abs(a[i]-b[i]);
 return sum/a.length;
}
function match(samples,refs){
 if(!Array.isArray(samples)||!samples.length||!refs.length)return {name:null,alternatives:[],score:null};
 const ranked=refs.map(r=>{
  let best=256;
  for(const sample of samples)best=Math.min(best,difference(sample,r.rgb));
  return {name:r.name,score:best};
 }).sort((a,b)=>a.score-b.score);
 const best=ranked[0],second=ranked[1];
 // Conservative: image suggestions are NOT proof of an exact same portrait.
 // Only near-pixel-identical source art with a strong margin can be preset.
 const certain=best.score<=30&&(!second||second.score-best.score>=9);
 return {name:certain?best.name:null,score:best.score,
  alternatives:ranked.slice(0,3).map(v=>v.name),confidence:certain?'high':'unverified'};
}
async function enrich(tiles){
 const refs=await data();
 for(const t of tiles){
  if(!t.portraitCandidates?.length)continue;
  const result=match(t.portraitCandidates,refs);
  t.name=result.name||t.name||'';
  t.nameConfidence=result.confidence;
  t.suggestions=result.alternatives;
  t.matchScore=result.score;
 }
 return {available:refs.length,matched:tiles.filter(t=>t.name).length};
}
root.NRW_BEAR_PORTRAIT_MATCHER={data,candidates,match,enrich,version:'wiki-12px-conservative'};
})(window);
